Repository esl/MongooseIM, pull requests merged in 2018-03, with the labels that each got.

#1746 Fix token cleanup on remove_user hook.
  src/mod_auth_token.erl
Labels: waiting-for-review

#1745 Fix path to repo dir in test makefile.
  test.disabled/ejabberd_tests/Makefile
Labels: waiting-for-review

#1744 Make HTTP one-to-one messages handler use the accumulator
  src/mongoose_client_api_messages.erl
Labels: waiting-for-review

#1749 Add codecov integration
  .gitignore
  .travis.yml
  README.md
  test.disabled/ejabberd_tests/run_common_test.erl
Labels: waiting-for-review

#1747 Run riak in a docker container for CI
  .travis.yml
  src/mongoose_riak.erl
  test.disabled/ejabberd_tests/test.config
  tools/db_configs/riak/riak.conf
  tools/db_configs/riak/riak.conf.ssl
  tools/setup_riak
  tools/travis-setup-db.sh
  tools/wait_for_healthcheck.sh
Labels: waiting-for-review

#1750 Fix a race condition in a call to GD conn manager
  src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
  src/global_distrib/mod_global_distrib_server_mgr.erl
  src/global_distrib/mod_global_distrib_server_sup.erl
Labels: global distribution, waiting-for-review

#1756 Try escalus with 5s stanza wait timeout
  test.disabled/ejabberd_tests/rebar.config
Labels: ready

#1740 Fix complete attribute calculation for backward pagination in MAM
  src/mam_iq.erl
  src/mod_mam.erl
  src/mod_mam_muc.erl
  src/mod_mam_utils.erl
  test.disabled/ejabberd_tests/test.config
  test.disabled/ejabberd_tests/tests/mam_SUITE.erl
  test.disabled/ejabberd_tests/tests/mam_helper.erl
  test.disabled/ejabberd_tests/tests/mam_helper.hrl
Labels: MAM, waiting-for-review

#1753 Update fast_tls to 1.0.20 and cache_tab to 1.0.12
  rebar.config
  rebar.lock
Labels: waiting-for-review

#1724 Use different config entry for advertised endpoints
  doc/modules/mod_global_distrib.md
  src/global_distrib/mod_global_distrib_mapping.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/global_distrib/mod_global_distrib_server_mgr.erl
  src/global_distrib/mod_global_distrib_utils.erl
  test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
Labels: global distribution, ready

#1757 Pass PRESET variable to codecov to distinguish builds
  .travis.yml
Labels: waiting-for-review

#1761 Change Global Distribution loglevels + some new logs
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/global_distrib/mod_global_distrib_server_mgr.erl
  src/global_distrib/mod_global_distrib_utils.erl
  src/mongoose_metrics.erl
Labels: global distribution, ready

#1763 Make packet_to_component GD handler more robust
  rel/reg1.vars.config
  src/global_distrib/mod_global_distrib.erl
  src/global_distrib/mod_global_distrib_bounce.erl
  src/global_distrib/mod_global_distrib_utils.erl
  src/mongoose_acc.erl
  test.disabled/ejabberd_tests/tests/component_SUITE.erl
  test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
Labels: global distribution, waiting-for-review

#1760 Move all path related functions into path_helper in big tests
  test.disabled/ejabberd_tests/Makefile
  test.disabled/ejabberd_tests/run_common_test.erl
  test.disabled/ejabberd_tests/src/ct_mongoose_log_hook.erl
  test.disabled/ejabberd_tests/tests/ejabberd_node_utils.erl
  test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
  test.disabled/ejabberd_tests/tests/path_helper.erl
  test.disabled/ejabberd_tests/tests/reload_helper.erl
  tools/abs_dirpath.sh
Labels: waiting-for-review

#1660 Create pool on receiving
  doc/modules/mod_global_distrib.md
  src/global_distrib/mod_global_distrib.erl
  src/global_distrib/mod_global_distrib_hosts_refresher.erl
  src/global_distrib/mod_global_distrib_mapping.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
  src/global_distrib/mod_global_distrib_sender.erl
  src/global_distrib/mod_global_distrib_server_mgr.erl
  src/global_distrib/mod_global_distrib_server_sup.erl
  test.disabled/ejabberd_tests/tests/mod_global_distrib_SUITE.erl
Labels: global distribution, waiting-for-review

#1748 Fix saving unicode MAM messages.
  src/mod_mam_muc_odbc_arch.erl
  src/mod_mam_odbc_arch.erl
  src/mod_mam_riak_timed_arch_yz.erl
  src/mod_mam_utils.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/mongoose_rdbms_pgsql.erl
  test.disabled/ejabberd_tests/tests/mam_SUITE.erl
Labels: ready

#1768 Eradicate relative paths for small tests
  test/auth_jwt_SUITE.erl
  test/component_reg_SUITE.erl
  test/small_path_helper.erl
Labels: waiting-for-review

#1770 Add missing GD small suite
  test/mod_global_distrib_SUITE.erl
Labels: global distribution, waiting-for-review

#1758 Separated database logic from mod_muc into backend modules
  .travis.yml
  doc/modules/mod_muc.md
  include/mod_muc.hrl
  src/mod_muc.erl
  src/mod_muc_db.erl
  src/mod_muc_db_mnesia.erl
  src/mod_muc_room.erl
  test.disabled/ejabberd_tests/tests/muc_SUITE.erl
  test.disabled/ejabberd_tests/tests/muc_helper.erl
  test.disabled/ejabberd_tests/tests/s2s_SUITE.erl
  test.disabled/ejabberd_tests/tests/s2s_helper.erl
Labels: waiting-for-review

#1775 Introduce 'foreground' mode
  doc/user-guide/Getting-started.md
  rel/files/mongooseim
  rel/files/mongooseimctl
Labels: waiting-for-review

#1742 Test http admin + muc light odbc backend
  doc/rest-api/Administration-backend_swagger.yml
  test.disabled/ejabberd_tests/tests/muc_light_http_api_SUITE.erl
Labels: tests, waiting-for-review
