Repository esl/MongooseIM, pull requests merged in 2018-11, with the labels that each got.

#2119 [clt-rabbit] Don't crash RMQ worker when amqp exception occurs
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_amqp.erl
  src/mongoose_rabbit_worker.erl
  test/mongoose_rabbit_worker_SUITE.erl
Labels: clt-rabbit

#1553 Remove unnecessary TODOs
  src/auth/ejabberd_auth_external.erl
  src/gen_mod.erl
Labels: WIP :construction:

#2121 [clt-rabbit] Switch mod_event_pusher_rabbit to mongoose_wpool
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  doc/advanced-configuration/outgoing-connections.md
  doc/modules/mod_event_pusher_rabbit.md
  mkdocs.yml
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_rabbit_worker.erl
  src/wpool/mongoose_wpool_rabbit.erl
  test/mongoose_rabbit_worker_SUITE.erl
Labels: clt-rabbit

#2036 More error resilient test runner
  big_tests/rebar.config
  tools/test-runner.sh
  tools/test_runner/complete-test-name.sh
  tools/test_runner/complete_test_name.erl
  tools/test_runner/selected-tests-to-test-spec.sh
  tools/test_runner/selected_tests_to_test_spec.erl
Labels: WIP :construction:

#2075 Dialyzer 21 fixes
  .travis.yml
  src/auth/ejabberd_auth_external.erl
  src/ejabberd_c2s.erl
  src/ejabberd_ctl.erl
  src/jlib.erl
  src/mod_amp.erl
  src/mod_blocking.erl
  src/mod_last.erl
  src/mod_muc.erl
  src/mod_muc_room.erl
  src/mongoose_cluster.erl
  src/muc_light/mod_muc_light.erl
  src/muc_light/mod_muc_light_commands.erl
  src/muc_light/mod_muc_light_room.erl
  src/muc_light/mod_muc_light_utils.erl
  src/rdbms/mongoose_rdbms.erl
  src/sasl/cyrsasl.erl
Labels: ready

#2123 Do not load bash completion from brew in Mac OS if it is already loaded
  tools/test-runner-complete.sh
Labels: waiting-for-review

#1527 Listener Modules doc refactor
  doc/advanced-configuration/Listener-modules.md
Labels: WIP :construction:, doc

#2122 Refactor PubSub code to prepare for RDBMS
  include/pubsub.hrl
  src/jid.erl
  src/pubsub/gen_pubsub_node.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/node_flat.erl
  src/pubsub/node_push.erl
Labels: refactoring, waiting-for-review

#2125 [clt-rabbit] Add overflow prevention mechanism to RMQ worker
  src/mongoose_rabbit_worker.erl
  src/wpool/mongoose_wpool_rabbit.erl
  test/mongoose_rabbit_worker_SUITE.erl
Labels: clt-rabbit

#1308 Set Sec-Websocket-Protocol header according RFC
  src/mod_websockets.erl
  test/mod_websockets_SUITE.erl
Labels: bug, waiting-for-review

#2126 Extract pubsub_item table operation to pubsub's mnesia backend
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/node_flat.erl
Labels: ready

#2133 Cover `item_publisher` option with tests
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/pubsub_tools.erl
Labels: waiting-for-ci, waiting-for-review

#2129 pubsub_state RDBMS backend
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/muc_helper.erl
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/muc_light_http_api_SUITE.erl
  big_tests/tests/muc_light_legacy_SUITE.erl
  big_tests/tests/pep_SUITE.erl
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/push_integration_SUITE.erl
  doc/modules/mod_pubsub.md
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  src/jid.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/mod_pubsub_db_rdbms_sql.erl
  src/pubsub/node_flat.erl
  src/pubsub/node_pep.erl
  src/pubsub/node_push.erl
Labels: waiting-for-review

#2136 Optimise pubsub's node removal
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/mod_pubsub_db_rdbms_sql.erl
  src/pubsub/node_flat.erl
Labels: waiting-for-review

#2138 update deps
  rebar.config
  rebar.lock
Labels: community, ready, waiting-for-ci

#2141 Pubsub node mnesia backend
  rel/files/app.config
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/nodetree_dag.erl
  src/pubsub/nodetree_tree.erl
Labels: waiting-for-ci, waiting-for-review

#2142 Extended PubSub tests to cover Mnesia + #pubsub_node usage
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  src/pubsub/gen_pubsub_nodetree.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/node_hometree.erl
  src/pubsub/nodetree_dag.erl
  src/pubsub/nodetree_tree.erl
Labels: waiting-for-ci, waiting-for-review
