Repository esl/MongooseIM, pull requests merged in 2018-05, with the labels that each got.

#1413 Fix http muc tests
  big_tests/tests/muc_SUITE.erl
  src/mongoose_http_client.erl
Labels: ready, waiting-for-ci

#1729 Update exml to rapidxml based version.
  big_tests/tests/oauth_SUITE.erl
  rebar.config
  rebar.lock
  src/mongoose_api_format.erl
  test/acc_SUITE.erl
Labels: WIP

#1832 Fix broken lager_console_backend backend
  rel/files/app.config
Labels: bug, waiting-for-review

#1816 Fix ODBC API support for MongooseIM
  .travis.yml
  big_tests/default.spec
  big_tests/test.config
  big_tests/tests/last_SUITE.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mod_blocking_SUITE.erl
  big_tests/tests/offline_SUITE.erl
  big_tests/tests/rdbms_SUITE.erl
  doc/modules/mod_mam.md
  doc/user-guide/How-to-build.md
  doc/user-guide/release_config.md
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  rebar.config
  rebar.lock
  src/ejabberd_auth_odbc.erl
  src/ejabberd_rdbms.erl
  src/mod_auth_token_odbc.erl
  src/mod_last_odbc.erl
  src/mod_mam_muc_odbc_arch.erl
  src/mod_mam_odbc_arch.erl
  src/mod_mam_odbc_async_pool_writer.erl
  src/mod_mam_odbc_prefs.erl
  src/mod_mam_odbc_user.erl
  src/mod_mam_utils.erl
  src/mod_muc_light_db_odbc_sql.erl
  src/mod_offline_odbc.erl
  src/mod_privacy_odbc.erl
  src/mod_private_mysql.erl
  src/mod_private_odbc.erl
  src/mod_roster.erl
  src/mod_roster_odbc.erl
  src/mod_vcard_odbc.erl
  src/mongoose_iq.erl
  src/rdbms/mongoose_rdbms.erl
  src/rdbms/mongoose_rdbms_mysql.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/rdbms_queries.erl
  src/rdbms/rdbms_queries_mssql.erl
  test/mongoose_rdbms_SUITE.erl
  tools/configure
  tools/travis-setup-db.sh
  tools/travis-test.sh
Labels: ready, waiting-for-ci

#1835 Add copyright and author notices for mod_jingle_sip
  doc/advanced-configuration/Modules.md
  doc/modules/mod_jingle_sip.md
  src/jingle_sip/jingle_sip_callbacks.erl
  src/jingle_sip/jingle_sip_helper.erl
  src/jingle_sip/jingle_to_sdp.erl
  src/jingle_sip/mod_jingle_sip.erl
  src/jingle_sip/mod_jingle_sip_backend.erl
  src/jingle_sip/sip_to_jingle.erl
Labels: ready, waiting-for-ci

#1802 Allow to enable preset on just some nodes
  big_tests/run_common_test.erl
Labels: ready

#1838 Improved ODBC support - round 2
  .travis.yml
  big_tests/default.spec
  big_tests/test.config
  big_tests/tests/last_SUITE.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mod_blocking_SUITE.erl
  big_tests/tests/offline_SUITE.erl
  big_tests/tests/rdbms_SUITE.erl
  doc/modules/mod_mam.md
  doc/user-guide/How-to-build.md
  doc/user-guide/release_config.md
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  rebar.config
  rebar.lock
  src/ejabberd_auth_odbc.erl
  src/ejabberd_rdbms.erl
  src/mod_auth_token_odbc.erl
  src/mod_last_odbc.erl
  src/mod_mam_muc_odbc_arch.erl
  src/mod_mam_odbc_arch.erl
  src/mod_mam_odbc_async_pool_writer.erl
  src/mod_mam_odbc_prefs.erl
  src/mod_mam_odbc_user.erl
  src/mod_mam_utils.erl
  src/mod_muc_light_db_odbc_sql.erl
  src/mod_offline_odbc.erl
  src/mod_privacy_odbc.erl
  src/mod_private_mysql.erl
  src/mod_private_odbc.erl
  src/mod_roster.erl
  src/mod_roster_odbc.erl
  src/mod_vcard_odbc.erl
  src/rdbms/mongoose_rdbms.erl
  src/rdbms/mongoose_rdbms_mysql.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/rdbms_queries.erl
  src/rdbms/rdbms_queries_mssql.erl
  test/mongoose_rdbms_SUITE.erl
  tools/configure
  tools/travis-setup-db.sh
  tools/travis-test.sh
Labels: WIP, waiting-for-ci, waiting-for-review

#1798 Fixes to MUC configuration cancellation and form submission handling
  big_tests/rebar.config
  big_tests/tests/muc_SUITE.erl
  src/mod_muc_room.erl
Labels: ready, waiting-for-ci

#1821 Add hibernate_after listener opt with 0 default value.
  doc/advanced-configuration/Listener-modules.md
  include/ejabberd_c2s.hrl
  src/ejabberd_c2s.erl
  src/ejabberd_receiver.erl
  src/ejabberd_socket.erl
Labels: ready, waiting-for-ci

#1845 Remove priv/mysql-part.sql
  priv/mysql-part-muc.sql
  priv/mysql-part.sql
  src/mod_mam_odbc_arch.erl
Labels: waiting-for-ci, waiting-for-review

#1841 use already present origin_jid from acc instead of adding new field
  src/ejabberd_c2s.erl
  src/jingle_sip/mod_jingle_sip.erl
Labels: waiting-for-review

#1850 [clt-rabbit] Handle presence events with Rabbit
  big_tests/Makefile
  big_tests/default.spec
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  rebar.config
  rebar.lock
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_cassandra_sup.erl
  src/mongoose_rabbit_worker.erl
  src/mongoose_supervisor2.erl
  src/mongooseim.app.src
Labels: waiting-for-review

#1852 [skip ci] Update "How to build" page
  doc/user-guide/How-to-build.md
Labels: doc, waiting-for-review

#1846 Partial RPC cleanup in big tests
  big_tests/rebar.config
  big_tests/src/ct_mongoose_hook.erl
  big_tests/src/ct_tty_hook.erl
  big_tests/tests/acc_e2e_SUITE.erl
  big_tests/tests/amp_big_SUITE.erl
  big_tests/tests/bosh_SUITE.erl
  big_tests/tests/cluster_commands_SUITE.erl
  big_tests/tests/component_SUITE.erl
  big_tests/tests/component_helper.erl
  big_tests/tests/conf_reload_SUITE.erl
  big_tests/tests/connect_SUITE.erl
  big_tests/tests/distributed_helper.erl
  big_tests/tests/dynamic_modules.erl
  big_tests/tests/ejabberd_node_utils.erl
  big_tests/tests/ejabberdctl_SUITE.erl
  big_tests/tests/ejabberdctl_helper.erl
  big_tests/tests/jingle_SUITE.erl
  big_tests/tests/ldap_helper.erl
  big_tests/tests/login_SUITE.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/metrics_helper.erl
  big_tests/tests/metrics_register_SUITE.erl
  big_tests/tests/metrics_roster_SUITE.erl
  big_tests/tests/mod_aws_sns_SUITE.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mod_http_notification_SUITE.erl
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_helper.erl
  big_tests/tests/muc_light_helper.erl
  big_tests/tests/oauth_SUITE.erl
  big_tests/tests/pep_SUITE.erl
  big_tests/tests/presence_SUITE.erl
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_pubsub_SUITE.erl
  big_tests/tests/rest_helper.erl
  big_tests/tests/s2s_SUITE.erl
  big_tests/tests/s2s_helper.erl
  big_tests/tests/sasl_SUITE.erl
  big_tests/tests/shared_roster_SUITE.erl
  big_tests/tests/sic_SUITE.erl
  big_tests/tests/sm_SUITE.erl
  big_tests/tests/users_api_SUITE.erl
  big_tests/tests/vcard_SUITE.erl
  big_tests/tests/vcard_simple_SUITE.erl
  big_tests/tests/vcard_update.erl
Labels: WIP

#1851 [skip ci] SASL EXTERNAL docs
  doc/advanced-configuration/Listener-modules.md
  doc/authentication-backends/PKI-authentication-module.md
  doc/authentication-methods/client-certificate.md
  mkdocs.yml
Labels: doc, ready

#1783 Inbox draft
  big_tests/default.spec
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/muc_light_helper.erl
  doc/advanced-configuration/Modules.md
  doc/modules/mod_inbox.md
  include/mod_inbox.hrl
  include/mongoose_ns.hrl
  mkdocs.yml
  priv/mysql.sql
  priv/pg.sql
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_muclight.erl
  src/inbox/mod_inbox_odbc.erl
  src/inbox/mod_inbox_odbc_mysql.erl
  src/inbox/mod_inbox_odbc_pgsql.erl
  src/inbox/mod_inbox_one2one.erl
  src/inbox/mod_inbox_utils.erl
  src/mod_carboncopy.erl
  src/mod_mam_params.erl
  src/mod_mam_utils.erl
Labels: ready

#1662 Packaging MongooseIM
  .travis.yml
  tools/pkg/README.md
  tools/pkg/build
  tools/pkg/env/build-run
  tools/pkg/env/publish
  tools/pkg/files/build
  tools/pkg/packages/.keepme
  tools/pkg/platforms/centos6/Dockerfile
  tools/pkg/platforms/centos6/files/build/mongooseim.spec
  tools/pkg/platforms/centos6/files/build/rpmmacros.in
  tools/pkg/platforms/centos6/files/build/script.sh
  tools/pkg/platforms/centos6/files/build/sign.sh
  tools/pkg/platforms/centos6/files/scl-build
  tools/pkg/platforms/centos7/Dockerfile
  tools/pkg/platforms/centos7/files/build/mongooseim.spec
  tools/pkg/platforms/centos7/files/build/rpmmacros.in
  tools/pkg/platforms/centos7/files/build/script.sh
  tools/pkg/platforms/centos7/files/build/sign.sh
  tools/pkg/platforms/debian_stretch/Dockerfile
  tools/pkg/platforms/debian_stretch/files/build/debian/README.Debian
  tools/pkg/platforms/debian_stretch/files/build/debian/README.source
  tools/pkg/platforms/debian_stretch/files/build/debian/changelog
  tools/pkg/platforms/debian_stretch/files/build/debian/compat
  tools/pkg/platforms/debian_stretch/files/build/debian/control
  tools/pkg/platforms/debian_stretch/files/build/debian/copyright
  tools/pkg/platforms/debian_stretch/files/build/debian/docs
  tools/pkg/platforms/debian_stretch/files/build/debian/postinst
  tools/pkg/platforms/debian_stretch/files/build/debian/postrm
  tools/pkg/platforms/debian_stretch/files/build/debian/prerm
  tools/pkg/platforms/debian_stretch/files/build/debian/rules
  tools/pkg/platforms/debian_stretch/files/build/mongooseim.service
  tools/pkg/platforms/debian_stretch/files/build/script.sh
  tools/pkg/publish
  tools/pkg/run
  tools/travis-test.sh
Labels: tools, waiting-for-ci

#1849 Add configurable number of acceptors for listeners.
  doc/advanced-configuration/Listener-modules.md
  src/ejabberd_listener.erl
  src/mongoose_tcp_listener.erl
  src/mongoose_udp_listener.erl
  test/ejabberd_listener_SUITE.erl
Labels: ready

#1860 [WIP] Remove MAM 0.2
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  doc/modules/mod_mam.md
  include/mongoose_ns.hrl
  rel/files/ejabberd.cfg
  src/ejabberd_gen_mam_archive.erl
  src/mam_iq.erl
  src/mod_mam.erl
  src/mod_mam_cassandra_arch.erl
  src/mod_mam_meta.erl
  src/mod_mam_muc.erl
  src/mod_mam_odbc_arch.erl
  src/mod_mam_odbc_async_pool_writer.erl
  src/mod_mam_params.erl
  src/mod_mam_riak_timed_arch_yz.erl
  src/mod_mam_utils.erl
  src/mongoose_metrics.erl
  src/mongoose_metrics_mam_hooks.erl
  test/mod_mam_meta_SUITE.erl
Labels: MAM, ready, waiting-for-ci

#1842 Update Escalus in tests to 4.0.0.
  big_tests/rebar.config
  big_tests/tests/mod_http_upload_SUITE.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_light_legacy_SUITE.erl
Labels: ready, waiting-for-ci

#1883 Parallel pull for docker-compose
  tools/docker-compose.sh
  tools/travis-test.sh
Labels: waiting-for-ci, waiting-for-review

#1885 Use s3-parallel-put instead of aws-s3-sync
  tools/travis-upload-to-s3.sh
Labels: WIP

#1879 Skip install steps for pkg preset
  .travis.yml
Labels: waiting-for-ci, waiting-for-review

#1878 [clt-rabbit] Clear docs
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit

#1864 [clt-rabbit] Add initial version of load testing scenario for XMPP with RabbitMQ
  load_test/amoc_scenarios/xmpp_amqp.erl
Labels: clt-rabbit

#1873 Use mediumblob for mam message storage
  big_tests/src/assert_helper.erl
  big_tests/tests/mam_helper.hrl
  big_tests/tests/rdbms_SUITE.erl
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  rebar.config
  rebar.lock
  tools/db_configs/mysql/mysql.cnf
  tools/mssql-shell.sh
Labels: waiting-for-ci, waiting-for-review

#1886 Data on volume
  tools/db_configs/cassandra/proxy/zazkia-routes.json
  tools/db_configs/mysql/mysql.cnf
  tools/travis-setup-db.sh
Labels: waiting-for-ci, waiting-for-review

#1893 Reduce waiting time for cover on CI
  .travis.yml
  big_tests/run_common_test.erl
  src/mongoose_cover_helper.erl
Labels: waiting-for-ci, waiting-for-review

#1894 Remove undefined functions from exports
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit

#1889 [clt-rabbit] Handle group chat messages
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit
