Repository esl/MongooseIM, pull requests merged in 2018-08, with the labels that each got.

#1996 use gen fsm compat
  big_tests/Makefile
  big_tests/src/ejabberd_tests.app.src
  big_tests/tests/muc_helper.erl
  rebar.config
  rebar.lock
  src/ejabberd_receiver.erl
  src/ejabberd_s2s.erl
  src/ejabberd_s2s_in.erl
  src/mod_bosh_socket.erl
  src/mod_muc.erl
  src/mod_muc_room.erl
  src/mongooseim.app.src
Labels: WIP, community

#2010 fix spec
  src/xmpp_router.erl
Labels: community

#2007 Resend unacked on reconnection fix
  big_tests/tests/sm_SUITE.erl
  src/ejabberd_c2s.erl
Labels: waiting-for-ci, waiting-for-review

#2017 Inbox conversation hidden read
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_helper.erl
  doc/modules/mod_inbox.md
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_odbc.erl
Labels: waiting-for-review

#2002 Deps upgrade
  rebar.config
  rebar.lock
  src/auth/ejabberd_auth_jwt.erl
  src/cassandra/mongoose_cassandra.erl
  src/mod_muc_room.erl
  src/mongoose_api_json.erl
  src/mongoose_redis.erl
  src/mongooseim.app.src
  src/rdbms/mongoose_rdbms_pgsql.erl
  src/rdbms/mongoose_rdbms_pgsql_codec_boolean.erl
  test/auth_jwt_SUITE.erl
Labels: waiting-for-review

#2023 Add flush_time metric to MAM RDBMS async pool writers.
  doc/modules/mod_mam.md
  doc/operation-and-maintenance/Mongoose-metrics.md
  src/mam/mod_mam_muc_odbc_async_pool_writer.erl
  src/mam/mod_mam_odbc_async_pool_writer.erl
  src/rdbms/mongoose_rdbms.erl
Labels: waiting-for-review

#2024 Update monitoring docs and make them slightly more practical.
  doc/operation-and-maintenance/Logging-&-monitoring.md
  doc/operation-and-maintenance/example-grafana-graph.png
Labels: ready

#2030 Rest api muc light config
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/muc_light_helper.erl
  big_tests/tests/muc_light_legacy_SUITE.erl
  big_tests/tests/rest_client_SUITE.erl
  doc/rest-api/Client-frontend_swagger.yml
  rel/files/ejabberd.cfg
  src/mongoose_client_api_rooms.erl
  src/mongoose_client_api_rooms_config.erl
  src/muc_light/mod_muc_light.erl
  src/muc_light/mod_muc_light_commands.erl
  src/muc_light/mod_muc_light_room.erl
Labels: waiting-for-review

#2039 Technical documentation content review
  doc/Basic-configuration.md
  doc/Differentiators.md
  doc/user-guide/How-to-build.md
  doc/user-guide/release_config.md
Labels: waiting-for-review

#2038 Update ODBC and release config examples in docs
  doc/Advanced-configuration.md
  doc/user-guide/release_config.md
Labels: doc, waiting-for-review

#2037 Update rebar3 to 3.6.1
  rebar3
Labels: waiting-for-review

#1998 Remove legacy authentication
  big_tests/tests/connect_SUITE.erl
  big_tests/tests/legacy_stream_helper.erl
  big_tests/tests/login_SUITE.erl
  doc/user-guide/Features-and-supported-standards.md
  include/mongoose_ns.hrl
  src/auth/ejabberd_auth.erl
  src/auth/ejabberd_gen_auth.erl
  src/auth/extauth.erl
  src/ejabberd_c2s.erl
  src/sasl/cyrsasl_plain.erl
Labels: waiting-for-ci, waiting-for-review

#2047 Inbox total count unread
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_helper.erl
  doc/modules/mod_inbox.md
  include/mod_inbox.hrl
  src/inbox/mod_inbox.erl
Labels: waiting-for-ci

#2050 Update exml with security fix
  rebar.config
  rebar.lock
Labels: WIP, waiting-for-ci

#2042 Use eredis with Unix domain sockets support
  doc/modules/mod_global_distrib.md
  rebar.config
  rebar.lock
Labels: WIP, community

#2051 Fix checks for matching configuration before reload_cluster.
  src/config/mongoose_config_parser.erl
  src/config/mongoose_config_reload.erl
  src/ejabberd_config.erl
  test/ejabberd_config_SUITE.erl
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.loglevel_err.cfg
Labels: ready

#2046 send "not-authorized" error instead of "internal-error" in case of ba…
  src/auth/ejabberd_auth.erl
Labels: ready, waiting-for-ci

#2052 Inbox error description
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_helper.erl
  doc/modules/mod_inbox.md
  src/inbox/mod_inbox.erl
Labels: waiting-for-ci, waiting-for-review
