Repository esl/MongooseIM, pull requests merged in 2018-07, with the labels that each got.

#1956 Wait for expected HTTP status code after creating schema or index
  tools/setup_riak
Labels: waiting-for-ci, waiting-for-review

#1954 Catch timeout when stopping clients in bosh_SUITE:interleave_requests
  big_tests/tests/bosh_interleave_reqs.erl
Labels: waiting-for-review

#1953 Revert "fix ejabberd_logleverl_SUITE"
  test/ejabberd_loglevel_SUITE.erl
Labels: waiting-for-review

#1948 Handle node-specific options correctly in reload_cluster
  big_tests/tests/reload_helper.erl
  doc/developers-guide/flat_options.md
  doc/operation-and-maintenance/Reloading-configuration-on-a-running-system.md
  include/ejabberd_config.hrl
  src/config/mongoose_config_flat.erl
  src/config/mongoose_config_helper.erl
  src/config/mongoose_config_parser.erl
  src/config/mongoose_config_reload.erl
  src/config/mongoose_config_utils.erl
  src/ejabberd_admin.erl
  src/ejabberd_config.erl
  src/ejabberd_listener.erl
  src/gen_mod.erl
  src/gen_mod_deps.erl
  src/mongoose_cluster.erl
  test/ejabberd_config_SUITE.erl
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.gd.node1_v1.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_module_node1_v1.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_module_node2_v1.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_node1_v1.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_node1_v2.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_node2_v1.cfg
  test/ejabberd_config_SUITE_data/ejabberd.no_listeners.node_specific_node2_v2.cfg
  test/ejabberd_helper.erl
  test/mongoose_config_SUITE.erl
  tools/travis-test.sh
Labels: waiting-for-review

#1955 Unify pool deps
  big_tests/tests/mam_helper.erl
  big_tests/tests/push_pubsub_SUITE.erl
  include/mongoose.hrl
  include/mongoose_wpool.hrl
  rebar.config
  rebar.lock
  src/auth/ejabberd_auth_http.erl
  src/ejabberd_app.erl
  src/ejabberd_redis.erl
  src/ejabberd_sm.erl
  src/ejabberd_sm_redis.erl
  src/mongoose_http_client.erl
  src/mongoose_http_client_sup.erl
  src/mongoose_http_client_worker.erl
  src/mongoose_redis.erl
  src/mongoose_riak.erl
  src/mongoose_riak_sup.erl
  src/mongoose_wpool.erl
  src/mongooseim.app.src
  test/ejabberd_sm_SUITE.erl
  test/http_client_SUITE.erl
  tools/configure
Labels: WIP

#1965 MSSQL support for Inbox
  big_tests/run_common_test.erl
  big_tests/tests/inbox_SUITE.erl
  doc/modules/mod_inbox.md
  priv/mssql2012.sql
  src/inbox/mod_inbox_odbc.erl
  src/inbox/mod_inbox_odbc_mssql.erl
  src/inbox/mod_inbox_odbc_mysql.erl
  src/inbox/mod_inbox_odbc_pgsql.erl
Labels: ready

#1776 Improve room http api
  big_tests/tests/rest_client_SUITE.erl
  doc/rest-api/Client-frontend_swagger.yml
  src/mongoose_client_api.erl
  src/mongoose_client_api_rooms.erl
  src/mongoose_client_api_rooms_messages.erl
  src/mongoose_client_api_rooms_users.erl
Labels: waiting-for-review

#1967 Fix randomly failing ejabberd_listeners_SUITE
  test/async_helper.erl
  test/ejabberd_listener_SUITE.erl
Labels: waiting-for-review

#1977 Add missing params support to mod_mam_meta
  src/mam/mod_mam_meta.erl
Labels: WIP

#1962 Incremental sleep redundancy
  big_tests/tests/bosh_SUITE.erl
  big_tests/tests/component_helper.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/metrics_register_SUITE.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mod_http_upload_SUITE.erl
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_integration_SUITE.erl
  big_tests/tests/sm_SUITE.erl
  big_tests/tests/users_api_SUITE.erl
Labels: WIP

#1973 Test runner
  .gitignore
  .travis.yml
  Makefile
  big_tests/Makefile
  big_tests/run_common_test.erl
  big_tests/test.config
  big_tests/tests/ct_helper.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/rdbms_SUITE.erl
  doc/developers-guide/Testing-MongooseIM.md
  tools/build-releases.sh
  tools/docker-compose.sh
  tools/kill_processes_on_exit.sh
  tools/print-dots.sh
  tools/setup-redis.sh
  tools/stop-nodes.sh
  tools/test-runner-complete.sh
  tools/test-runner.sh
  tools/test_runner/README.md
  tools/test_runner/complete-test-name.sh
  tools/test_runner/complete_test_name.erl
  tools/test_runner/list_presets.erl
  tools/test_runner/list_presets.sh
  tools/test_runner/list_suites.sh
  tools/test_runner/presets_to_dbs.erl
  tools/test_runner/presets_to_dbs.sh
  tools/test_runner/selected-tests-to-test-spec.sh
  tools/test_runner/selected_tests_to_test_spec.erl
  tools/test_runner/show_reports.sh
  tools/travis-build-tests.sh
  tools/travis-common-vars.sh
  tools/travis-setup-db.sh
  tools/travis-test.sh
Labels: waiting-for-ci, waiting-for-review

#1961 Muc inbox
  big_tests/tests/inbox_SUITE.erl
  doc/modules/mod_inbox.md
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_muc.erl
  src/inbox/mod_inbox_muclight.erl
  src/mod_muc_room.erl
Labels: waiting-for-ci, waiting-for-review

#1925 acc-related fixes and cleanups
  big_tests/tests/pep_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  src/ejabberd_local.erl
  src/ejabberd_router.erl
  src/ejabberd_sm.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/gen_iq_handler.erl
  src/mam/mod_mam_muc.erl
  src/mod_caps.erl
  src/mod_muc_iq.erl
  src/mod_muc_room.erl
  src/mod_offline.erl
  src/mod_ping.erl
  src/mod_roster.erl
  src/muc_light/mod_muc_light.erl
  test/mongoose_cleanup_SUITE.erl
Labels: WIP, refactoring

#1989 Fix test-runner test cases completion for inbox_SUITE
  big_tests/tests/inbox_SUITE.erl
Labels: waiting-for-ci, waiting-for-review

#1991 Add --colors option for test-runner
  tools/test-runner-complete.sh
  tools/test-runner.sh
Labels: waiting-for-review

#1970 Timestamp support in mod_inbox
  big_tests/tests/inbox.hrl
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_helper.erl
  doc/modules/mod_inbox.md
  include/mod_inbox.hrl
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_muclight.erl
  src/inbox/mod_inbox_odbc.erl
  src/inbox/mod_inbox_odbc_mssql.erl
  src/inbox/mod_inbox_odbc_mysql.erl
  src/inbox/mod_inbox_odbc_pgsql.erl
  src/inbox/mod_inbox_utils.erl
  src/jlib.erl
Labels: waiting-for-review
