Repository esl/MongooseIM, pull requests merged in 2018-02, with the labels that each got.

#1695 Fix missing disco replies between components in GD
  src/global_distrib/mod_global_distrib_disco.erl
  src/global_distrib/mod_global_distrib_mapping.erl
  src/global_distrib/mod_global_distrib_outgoing_conns_sup.erl
  src/global_distrib/mod_global_distrib_utils.erl
Labels: global distribution, waiting-for-review

#1697 Extend debug logs in ejd_service and mod_websockets
  src/ejabberd_service.erl
  src/mod_websockets.erl
Labels: global distribution, waiting-for-review

#1726 Don't try to push message without body
  src/event_pusher/mod_event_pusher_push.erl
Labels: waiting-for-review

#1727 Fix mod_event_pusher_push docs #1704 [skip-ci]
  doc/modules/mod_event_pusher_push.md
Labels: waiting-for-review

#1720 Replace is_result with is_iq_result
  test.disabled/ejabberd_tests/tests/push_SUITE.erl
  test.disabled/ejabberd_tests/tests/push_integration_SUITE.erl
  test.disabled/ejabberd_tests/tests/push_pubsub_SUITE.erl
Labels: refactoring, tests, waiting-for-review

#1621 Allow spaces in install dir name
  rel/files/erl
  rel/files/mongooseim
  rel/files/mongooseimctl
  rel/files/nodetool
  tools/configure
Labels: ready

#1706 Import code paths for big test cover analyze
  test.disabled/ejabberd_tests/Makefile
  test.disabled/ejabberd_tests/run_common_test.erl
Labels: ready, refactoring

#1737 Put node starting code into a separate script
  tools/start-nodes.sh
  tools/travis-common-vars.sh
  tools/travis-test.sh
Labels: waiting-for-review

#1708 Remove jlib including from inside big tests
  test.disabled/ejabberd_tests/tests/vcard_SUITE.erl
Labels: ready, refactoring

#1715 Print more debug information when an error is caught in mod_vcard
  src/mod_vcard.erl
Labels: ready, refactoring

#1709 [skip ci] Fixed compliance xep number, removed caveat
  doc/user-guide/Features-and-supported-standards.md
Labels: ready

#1702 Allow uploading test reports to Google Drive.
  .travis.yml
  doc/developers-guide/Testing-MongooseIM.md
  tools/travis-build-and-push-docker.sh
  tools/travis-helpers.sh
  tools/travis-prepare-log-dir.sh
  tools/travis-secure-erase.sh
  tools/travis-test.sh
  tools/travis-upload-to-gdrive.sh
  tools/travis-upload-to-s3.sh
Labels: waiting-for-review
