Repository esl/MongooseIM, pull requests merged in 2018-12, with the labels that each got.

#2148 Refactor PubSub subscriptions options implementation
  include/pubsub.hrl
  src/jlib.erl
  src/pubsub/gen_pubsub_node.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/node_flat.erl
  src/pubsub/pubsub_form_utils.erl
  src/pubsub/pubsub_subscription.erl
Labels: waiting-for-ci, waiting-for-review

#2144 Pubsub last item cache
  big_tests/tests/pep_SUITE.erl
  big_tests/tests/pubsub_SUITE.erl
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_cache.erl
  src/pubsub/mod_pubsub_cache_mnesia.erl
  src/pubsub/mod_pubsub_cache_rdbms.erl
Labels: waiting-for-ci, waiting-for-review

#1027 add opts_for_module/2 and return opts on stop_module
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/rest_SUITE.erl
  src/gen_mod.erl
  test/gen_mod_SUITE.erl
Labels: community, waiting-for-review

#2167 Post-pubsub-subscription docs update
  doc/modules/mod_pubsub.md
Labels: waiting-for-review
