Repository esl/MongooseIM, pull requests merged in 2018-06, with the labels that each got.

#1901 [clt-rabbit] Fix a typo
  src/event_pusher/mod_event_pusher_rabbit.erl
Labels: clt-rabbit

#1896 Update lager to version 3.6.2
  rebar.config
  rebar.lock
  rel/files/app.config
Labels: waiting-for-review

#1895 Erradicate registered_users warnings in tests
  big_tests/tests/last_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/pep_SUITE.erl
  big_tests/tests/s2s_SUITE.erl
Labels: waiting-for-review

#1897 Fix database deadlock handling in mod_mam_odbc_prefs
  src/mod_mam_odbc_prefs.erl
Labels: waiting-for-review

#1899 Dockerize LDAP
  big_tests/test.config
  tools/travis-common-vars.sh
  tools/travis-setup-db.sh
  tools/travis-setup-ldap.sh
Labels: waiting-for-ci, waiting-for-review

#1908 Fix travis scripts on macosx
  tools/db_configs/cassandra/docker_entry.sh
  tools/travis-common-vars.sh
  tools/travis-setup-db.sh
  tools/travis-setup-ldap.sh
  tools/wait_for_service.sh
Labels: waiting-for-ci, waiting-for-review

#1900 ElasticSearch MAM backend
  .travis.yml
  big_tests/default.spec
  big_tests/test.config
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mongoose_elasticsearch_SUITE.erl
  doc/Advanced-configuration.md
  doc/advanced-configuration/database-backends-configuration.md
  doc/modules/mod_mam.md
  priv/elasticsearch/muc.json
  priv/elasticsearch/pm.json
  rebar.config
  rebar.lock
  rel/files/ejabberd.cfg
  rel/vars.config.in
  src/ejabberd_app.erl
  src/ejabberd_config.erl
  src/elasticsearch/mongoose_elasticsearch.erl
  src/mod_mam_elasticsearch_arch.erl
  src/mod_mam_meta.erl
  src/mod_mam_muc_elasticsearch_arch.erl
  src/mongooseim.app.src
  tools/configure
  tools/travis-setup-db.sh
Labels: waiting-for-ci

#1903 Jingle sip reINVITE
  big_tests/tests/jingle_SUITE.erl
  big_tests/tests/jingle_helper.erl
  big_tests/tests/jingle_sip_translator.erl
  src/jingle_sip/jingle_sip_callbacks.erl
  src/jingle_sip/mod_jingle_sip.erl
Labels: waiting-for-review

#1905 Strict control for starting supervised processes
  big_tests/tests/muc_helper.erl
  src/cassandra/mongoose_cassandra_sup.erl
  src/ejabberd_auth_http.erl
  src/ejabberd_auth_ldap.erl
  src/ejabberd_listener.erl
  src/ejabberd_rdbms.erl
  src/ejabberd_sup.erl
  src/ejabberd_users.erl
  src/global_distrib/mod_global_distrib_bounce.erl
  src/global_distrib/mod_global_distrib_hosts_refresher.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/global_distrib/mod_global_distrib_receiver.erl
  src/mod_caps.erl
  src/mod_mam_cache_user.erl
  src/mod_mam_muc_cache_user.erl
  src/mod_muc.erl
  src/mod_muc_log.erl
  src/mod_offline.erl
  src/mod_pubsub.erl
  src/mod_shared_roster_ldap.erl
  src/mod_vcard.erl
  src/mongoose_http_client.erl
  src/mongoose_riak_sup.erl
  src/rdbms/mongoose_rdbms.erl
Labels: waiting-for-ci, waiting-for-review

#1911 Fix a race condition in mod_global_distrib_SUITE:test_muc_conversation_history
  big_tests/tests/mod_global_distrib_SUITE.erl
Labels: ci-errors, waiting-for-review

#1909 [clt-rabbit] Add documentation for mod_event_pusher Rabbit backend
  doc/advanced-configuration/Modules.md
  doc/modules/mod_event_pusher_rabbit.md
Labels: clt-rabbit

#1216 replace Eldap custom implementation with the one provided by OTP
  asn1/ELDAPv3.asn1
  big_tests/tests/ldap_helper.erl
  big_tests/tests/vcard_SUITE.erl
  doc/Advanced-configuration.md
  include/eldap.hrl
  src/ejabberd_auth_ldap.erl
  src/eldap.erl
  src/eldap_filter.erl
  src/eldap_filter_yecc.yrl
  src/eldap_pool.erl
  src/eldap_utils.erl
  src/mod_shared_roster_ldap.erl
  src/mod_vcard_ldap.erl
  src/mongooseim.app.src
Labels: ready, waiting-for-ci

#1904 Remove the check which compares Mnesia directory with the value set in the app env when deleting Mnesia files
  src/mongoose_cluster.erl
Labels: ready, waiting-for-ci

#1906 Add some logging docs
  doc/developers-guide/logging.md
  mkdocs.yml
Labels: ready, squash-me

#1913 Use escalus c761b6068c4cbda18b58deaa87748df24c16c576
  big_tests/rebar.config
  big_tests/rebar.lock
Labels: waiting-for-ci, waiting-for-review

#1916 Comment reports link and a list of failed tests to Github
  .travis.yml
  big_tests/default.spec
  big_tests/src/ct_markdown_errors_hook.erl
  tools/travis-helpers.sh
  tools/travis-publish-github-comment.sh
Labels: WIP

#1914 Login suite refactoring and stabilisation
  big_tests/default.spec
  big_tests/tests/accounts_SUITE.erl
  big_tests/tests/login_SUITE.erl
  rel/files/ejabberd.cfg
  rel/mim1.vars.config
  src/mod_register.erl
Labels: WIP

#1917 Stabilizing MUC light transaction on MSSQL
  big_tests/tests/muc_light_http_api_SUITE.erl
  doc/advanced-configuration/database-backends-configuration.md
  src/mod_muc_light_db_odbc.erl
  src/mongoose_commands.erl
  tools/travis-setup-db.sh
Labels: ready, waiting-for-ci

#1902 [clt-rabbit] Logs and metrics
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit

#1921 Add stats into github comment
  big_tests/run_common_test.erl
  tools/travis-publish-github-comment.sh
Labels: waiting-for-ci, waiting-for-review

#1920 Increase wait time continuously
  big_tests/tests/metrics_register_SUITE.erl
  big_tests/tests/mongoose_helper.erl
  src/mod_register.erl
Labels: waiting-for-ci, waiting-for-review

#1926 Add VERBOSE=1 env variable to our build and test scripts
  Makefile
  big_tests/Makefile
  big_tests/run_common_test.erl
  big_tests/src/dedup_proxy_group_leader.erl
  tools/silent_exec.sh
Labels: waiting-for-ci, waiting-for-review

#1919 Fix async pool writer
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  doc/modules/mod_mam.md
  src/mod_mam_muc_odbc_async_pool_writer.erl
  src/mod_mam_odbc_async_pool_writer.erl
Labels: waiting-for-review

#1928 [clt-rabbit] Change metrics names
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit

#1929 Use https:// instead of git:// for deps
  .travis.yml
  big_tests/rebar.config
  big_tests/rebar.lock
  rebar.config
  rebar.lock
Labels: waiting-for-ci, waiting-for-review

#1935 Clt rabbit update amqp scenario
  load_test/amoc_scenarios/xmpp_amqp.erl
Labels: clt-rabbit

#1898 Ported User Leave and Join muc hooks from ejabberd
  doc/developers-guide/hooks_description.md
  src/mod_muc_room.erl
Labels: WIP, contribution

#1936 Language refactor of MAM async worker description
  doc/modules/mod_mam.md
Labels: doc, waiting-for-review

#1937 Wait for Alice archive in full text archive search test
  big_tests/tests/mam_SUITE.erl
Labels: waiting-for-review

#1943 stabilise pubsub_SUITE
  big_tests/tests/pubsub_SUITE.erl
Labels: waiting-for-review

#1931 Fix roster update on subscription request
  big_tests/tests/presence_SUITE.erl
  src/mod_roster_mnesia.erl
  src/mod_roster_odbc.erl
  src/mod_roster_riak.erl
Labels: waiting-for-ci, waiting-for-review

#1933 Use escalus with new cleanup system
  big_tests/rebar.config
  big_tests/rebar.lock
Labels: WIP

#1944 stabilise amp_big_SUITE
  big_tests/tests/amp_big_SUITE.erl
Labels: WIP

#1940 MongoosePush mock
  big_tests/services/mongoose_push-compose.yml
  big_tests/tests/mongoose_push_mock.erl
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_integration_SUITE.erl
  src/ejabberd_sup.erl
Labels: waiting-for-ci

#1950 Fix commenter for tasks that only run big or only small tests
  tools/travis-publish-github-comment.sh
Labels: waiting-for-review
