Repository esl/MongooseIM, pull requests merged in 2018-09, with the labels that each got.

#2000 mongoose_bin module
  src/admin_extra/service_admin_extra_accounts.erl
  src/admin_extra/service_admin_extra_stanza.erl
  src/auth/extauth.erl
  src/ejabberd_c2s.erl
  src/ejabberd_local.erl
  src/ejabberd_s2s_in.erl
  src/ejabberd_s2s_out.erl
  src/ejabberd_service.erl
  src/mod_caps.erl
  src/mod_commands.erl
  src/mod_muc.erl
  src/mod_roster.erl
  src/mongoose_bin.erl
  src/muc_light/mod_muc_light.erl
  src/muc_light/mod_muc_light_codec_legacy.erl
  src/muc_light/mod_muc_light_codec_modern.erl
  src/muc_light/mod_muc_light_db_mnesia.erl
  src/muc_light/mod_muc_light_db_rdbms.erl
  src/muc_light/mod_muc_light_room.erl
  src/muc_light/mod_muc_light_utils.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/node_flat.erl
  src/pubsub/node_hometree.erl
  src/randoms.erl
  src/sasl/cyrsasl_anonymous.erl
  src/sasl/cyrsasl_digest.erl
  src/str.erl
  test/ejabberd_c2s_SUITE_mocks.erl
  test/mongoose_cleanup_SUITE.erl
Labels: waiting-for-ci, waiting-for-review

#2060 Mongoose wpool abstraction
  big_tests/tests/mod_global_distrib_SUITE.erl
  src/auth/ejabberd_auth_http.erl
  src/event_pusher/mod_event_pusher_push.erl
  src/event_pusher/mod_event_pusher_sns.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/mod_push_service_mongoosepush.erl
  src/mongoose_http_client.erl
  src/mongoose_redis.erl
  src/mongoose_riak.erl
  src/mongoose_wpool.erl
  test/auth_external_SUITE.erl
  test/auth_http_SUITE.erl
  test/mod_aws_sns_SUITE.erl
  test/mongoose_wpool_SUITE.erl
Labels: WIP

#2069 Restore ?TCP_SEND_TIMEOUT use.
  src/ejabberd_listener.erl
  src/mongoose_tcp_listener.erl
Labels: waiting-for-review

#2043 Refactor Cassandra pools to use worker_pool
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/mam_helper.erl
  big_tests/tests/mongoose_cassandra_SUITE.erl
  src/cassandra/mongoose_cassandra.erl
  src/cassandra/mongoose_cassandra_pool.erl
  src/cassandra/mongoose_cassandra_sup.erl
  src/cassandra/mongoose_cassandra_worker.erl
Labels: refactoring, waiting-for-review

#2073 Codecov plugin
  .travis.yml
  big_tests/Makefile
  big_tests/run_common_test.erl
  rebar.config
  test/codecov_helper.erl
  tools/travis-test.sh
Labels: ready

#2079 Allow to configure ElasticSearch pool via outgoing_options
  big_tests/test.config
  big_tests/tests/mongoose_elasticsearch_SUITE.erl
  doc/Advanced-configuration.md
  doc/advanced-configuration/outgoing-connections.md
  doc/migrations/3.1.1_3.1.1++.md
  src/elasticsearch/mongoose_elasticsearch.erl
  src/mongoose_wpool.erl
  src/mongoose_wpool_elastic.erl
Labels: waiting-for-review

#2081 Remove debug log about old shapers
  src/shaper_srv.erl
Labels: waiting-for-ci, waiting-for-review

#2082 Reorganise certs generation
  .gitignore
  Makefile
  big_tests/Makefile
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mongoose_push_mock.erl
  big_tests/vm.dist.args.in
  rebar.config
  src/global_distrib/mod_global_distrib_connection.erl
  test/auth_jwt_SUITE.erl
  tools/db_configs/cassandra/docker_entry.sh
  tools/ssl/Makefile
  tools/ssl/openssl-ca.cnf
  tools/ssl/openssl-mongooseim.cnf
  tools/travis-setup-db.sh
Labels: waiting-for-review

#2087 Make elastic pool more generic :ok_hand:
  big_tests/test.config
  big_tests/tests/mongoose_elasticsearch_SUITE.erl
  doc/advanced-configuration/outgoing-connections.md
  doc/migrations/3.1.1_3.1.1++.md
  src/elasticsearch/mongoose_elasticsearch.erl
  src/mongoose_wpool_elastic.erl
Labels: waiting-for-review

#2067 [clt-rabbit] Improve mod_event_pusher_rabbit test suite
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
Labels: clt-rabbit

#2061 Stabilise cowboy_SUITE
  test/cowboy_SUITE.erl
Labels: waiting-for-review

#2088 Upgrade cowboy to 2.4.0 in tests
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/http_helper.erl
  big_tests/tests/mongoose_push_mock.erl
Labels: waiting-for-ci, waiting-for-review

#2085 SASL EXTERNAL E2E tests
  big_tests/default.spec
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/sasl_external_SUITE.erl
  big_tests/tests/sasl_external_SUITE_data/openssl-user.cnf
  big_tests/tests/sasl_external_SUITE_data/sign_cert.sh
  rel/files/mongooseim.cfg
  rel/vars.config.in
  src/sasl/cyrsasl_external.erl
  tools/ssl/Makefile
  tools/ssl/openssl-ca-clients.cnf
Labels: waiting-for-ci, waiting-for-review
