Repository esl/MongooseIM, pull requests merged in 2018-10, with the labels that each got.

#2092 Use escalus with gun for bosh
  big_tests/rebar.config
  big_tests/rebar.lock
Labels: waiting-for-review

#2093 SASL EXTERNAL for WebSockets and BOSH
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/tests/sasl_external_SUITE.erl
  doc/authentication-methods/client-certificate.md
  include/mod_bosh.hrl
  src/ejabberd_c2s.erl
  src/ejabberd_socket.erl
  src/ejabberd_tls.erl
  src/mod_bosh.erl
  src/mod_bosh_socket.erl
  src/mod_websockets.erl
  src/mongoose_transport.erl
  src/sasl/cyrsasl_external.erl
  test/ejabberd_c2s_SUITE_mocks.erl
  test/mod_websockets_SUITE.erl
Labels: waiting-for-review

#2084 Configure RDBMS pools via `outgoing_pools` option.
  big_tests/test.config
  doc/Advanced-configuration.md
  doc/Basic-configuration.md
  doc/advanced-configuration/database-backends-configuration.md
  doc/advanced-configuration/outgoing-connections.md
  doc/migrations/3.1.1_3.1.1++.md
  rel/files/mongooseim.cfg
  src/backend_module.erl
  src/config/mongoose_config_parser.erl
  src/ejabberd_app.erl
  src/ejabberd_check.erl
  src/ejabberd_rdbms.erl
  src/inbox/mod_inbox_rdbms.erl
  src/mam/mod_mam_muc_rdbms_arch.erl
  src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_rdbms_async_pool_writer.erl
  src/mongoose_metrics.erl
  src/rdbms/mongoose_rdbms.erl
  src/rdbms/mongoose_rdbms_mysql.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/mongoose_rdbms_pgsql.erl
  src/rdbms/mongoose_rdbms_sup.erl
  src/wpool/mongoose_wpool.erl
  src/wpool/mongoose_wpool_cassandra.erl
  src/wpool/mongoose_wpool_elastic.erl
  src/wpool/mongoose_wpool_generic.erl
  src/wpool/mongoose_wpool_http.erl
  src/wpool/mongoose_wpool_rdbms.erl
  src/wpool/mongoose_wpool_redis.erl
  src/wpool/mongoose_wpool_riak.erl
  test/ejabberd_config_SUITE.erl
  test/ejabberd_sm_SUITE.erl
  test/mongoose_config_SUITE.erl
  test/mongoose_rdbms_SUITE.erl
  test/mongoose_wpool_SUITE.erl
Labels: waiting-for-review

#2100 Event pusher improvements
  big_tests/tests/push_http_SUITE.erl
  doc/modules/mod_event_pusher_http.md
  src/event_pusher/mod_event_pusher.erl
  src/event_pusher/mod_event_pusher_http.erl
  src/event_pusher/mod_event_pusher_http_defaults.erl
Labels: waiting-for-review

#1934 muc light user affiliation rework
  src/muc_light/mod_muc_light_utils.erl
Labels: refactoring, waiting-for-ci, waiting-for-review

#2078 Inbox push notifications
  big_tests/tests/mongoose_push_mock.erl
  big_tests/tests/muc_light_helper.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_integration_SUITE.erl
  src/event_pusher/mod_event_pusher.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_one2one.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_rdbms_pgsql.erl
  src/inbox/mod_inbox_utils.erl
  src/rdbms/mongoose_rdbms_pgsql.erl
Labels: waiting-for-ci, waiting-for-review

#2110 [clt-rabbit] Extend mod_event_pusher_rabbit configuration
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  doc/modules/mod_event_pusher_rabbit.md
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit

#2117 mongoose_wpool controlled restarts
  doc/developers-guide/mongoose_wpool.md
  doc/developers-guide/mongoose_wpool_supervision.svg
  mkdocs.yml
  rebar.config
  rebar.lock
  src/ejabberd_app.erl
  src/ejabberd_c2s.erl
  src/ejabberd_socket.erl
  src/ejabberd_sup.erl
  src/wpool/mongoose_wpool.erl
  src/wpool/mongoose_wpool_cassandra.erl
  src/wpool/mongoose_wpool_elastic.erl
  src/wpool/mongoose_wpool_generic.erl
  src/wpool/mongoose_wpool_http.erl
  src/wpool/mongoose_wpool_mgr.erl
  src/wpool/mongoose_wpool_rdbms.erl
  src/wpool/mongoose_wpool_redis.erl
  src/wpool/mongoose_wpool_riak.erl
  src/wpool/mongoose_wpool_sup.erl
  src/wpool/mongoose_wpool_type_sup.erl
  test/ejabberd_sm_SUITE.erl
  test/http_client_SUITE.erl
  test/mongoose_wpool_SUITE.erl
Labels: waiting-for-review

#2113 Add dynamic backend to mod_pubsub
  doc/modules/mod_pubsub.md
  src/pubsub/gen_pubsub_node.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/node_dag.erl
  src/pubsub/node_flat.erl
  src/pubsub/node_hometree.erl
  src/pubsub/node_pep.erl
  src/pubsub/node_push.erl
  src/pubsub/nodetree_tree.erl
Labels: waiting-for-review

#2116 [clt-rabbit] Refactor RabbitMQ event pusher backend
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/mongoose_amqp.erl
  src/mongoose_rabbit_worker.erl
Labels: clt-rabbit
