Repository esl/MongooseIM, pull requests merged in 2018-04, with the labels that each got.

#1777 Improve MongoosePush's logs on 4xx errors
  src/mod_push_service_mongoosepush.erl
Labels: waiting-for-review

#1787 Bump MySQL database driver version
  rebar.config
  rebar.lock
Labels: waiting-for-ci

#1771 otp-ish API for starting/stopping modules via gen_mod
  big_tests/tests/ejabberdctl_SUITE.erl
  big_tests/tests/login_SUITE.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/rest_SUITE.erl
  src/gen_mod.erl
  test/gen_mod_SUITE.erl
Labels: ready

#1796 Push notifications refactoring
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_integration_SUITE.erl
  big_tests/tests/push_pubsub_SUITE.erl
  doc/modules/mod_event_pusher_push.md
  src/event_pusher/mod_event_pusher.erl
  src/event_pusher/mod_event_pusher_http.erl
  src/event_pusher/mod_event_pusher_push.erl
  src/event_pusher/mod_event_pusher_push_plugin.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/event_pusher/mod_event_pusher_sns.erl
  test/mod_aws_sns_SUITE.erl
Labels: waiting-for-ci

#1806 Update fast_tls to stat-less version
  rebar.config
  rebar.lock
Labels: waiting-for-ci

#1807 MAM 0.2 deprecation: log deprecation message on IQ get as well
  src/mam_iq.erl
  src/mod_mam.erl
  src/mod_mam_muc.erl
  src/mod_mam_utils.erl
Labels: waiting-for-ci

#1797 Jingle SIP
  big_tests/default.spec
  big_tests/rebar.config
  big_tests/tests/dynamic_modules.erl
  big_tests/tests/jingle_SUITE.erl
  big_tests/tests/jingle_sip_translator.erl
  big_tests/tests/push_helper.erl
  doc/modules/mod_jingle_sip.md
  include/mongoose.hrl
  include/mongoose_ns.hrl
  rebar.config
  rebar.lock
  src/ejabberd_app.erl
  src/ejabberd_c2s.erl
  src/ejabberd_sm.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/jingle_sip/jingle_sip_callbacks.erl
  src/jingle_sip/jingle_sip_helper.erl
  src/jingle_sip/jingle_to_sdp.erl
  src/jingle_sip/mod_jingle_sip.erl
  src/jingle_sip/mod_jingle_sip_backend.erl
  src/jingle_sip/sip_to_jingle.erl
  tools/configure
Labels: waiting-for-ci, waiting-for-review

#1792 Mongoose service
  big_tests/tests/ejabberdctl_SUITE.erl
  doc/Advanced-configuration.md
  doc/advanced-configuration/Modules.md
  doc/advanced-configuration/Services.md
  doc/user-guide/ICE_tutorial/ejabberd.cfg
  doc/user-guide/MongooseIM-High-level-Architecture.md
  mkdocs.yml
  rel/files/ejabberd.cfg
  src/ejabberd_app.erl
  src/ejabberd_config.erl
  src/gen_mod.erl
  src/global_distrib/mod_global_distrib_hosts_refresher.erl
  src/mongoose_service.erl
  src/service_admin_extra.erl
  src/service_admin_extra_accounts.erl
  src/service_admin_extra_last.erl
  src/service_admin_extra_node.erl
  src/service_admin_extra_private.erl
  src/service_admin_extra_roster.erl
  src/service_admin_extra_sessions.erl
  src/service_admin_extra_srg.erl
  src/service_admin_extra_stanza.erl
  src/service_admin_extra_stats.erl
  src/service_admin_extra_vcard.erl
  test/mongoose_service_SUITE.erl
Labels: WIP

#1814 Remove esip from default build
  Makefile
  doc/modules/mod_jingle_sip.md
  tools/configure
Labels: waiting-for-review

#1813 Fix a race condition in rest_client_SUITE
  big_tests/tests/rest_client_SUITE.erl
Labels: bug, ci-errors, waiting-for-ci

#1808 Properly handle resource reusing between stories in ejabberdctl_SUITE
  big_tests/tests/cluster_commands_SUITE.erl
  big_tests/tests/ejabberdctl_SUITE.erl
  big_tests/tests/ejabberdctl_helper.erl
Labels: ci-errors, waiting-for-ci

#1817 Move policy-violation check from backend modules into mod_mam
  src/mod_mam.erl
  src/mod_mam_cassandra_arch.erl
  src/mod_mam_muc.erl
  src/mod_mam_muc_cassandra_arch.erl
  src/mod_mam_muc_odbc_arch.erl
  src/mod_mam_muc_odbc_async_pool_writer.erl
  src/mod_mam_odbc_arch.erl
  src/mod_mam_odbc_async_pool_writer.erl
  src/mod_mam_riak_timed_arch_yz.erl
  src/mod_mam_utils.erl
Labels: waiting-for-ci, waiting-for-review
