Repository esl/MongooseIM, pull requests merged in 2019-07, with the labels that each got.

#2322 Add `clusterState` metric
  big_tests/tests/metrics_api_SUITE.erl
  doc/operation-and-maintenance/Mongoose-metrics.md
  src/mongoose_metrics.erl
  src/mongoose_metrics_definitions.hrl
Labels: waiting-for-ci, waiting-for-review

#2357 then than
  doc/modules/mod_blocking.md
Labels: community

#2356 Maxmimum
  doc/modules/mod_bosh.md
Labels: community

#2376 Update "How to build" and MSSQL instructions
  doc/advanced-configuration/database-backends-configuration.md
  doc/developers-guide/Testing-MongooseIM.md
  doc/operation-and-maintenance/known-issues.md
  doc/user-guide/How-to-build.md
Labels: doc, waiting-for-review

#2268 Fix MUC Light "role" archived in MAM
  big_tests/tests/muc_helper.erl
  big_tests/tests/muc_light_helper.erl
  src/muc_light/mod_muc_light_codec_legacy.erl
  src/muc_light/mod_muc_light_codec_modern.erl
  src/muc_light/mod_muc_light_utils.erl
  test/muc_light_SUITE.erl
Labels: waiting-for-ci, waiting-for-review
