Repository esl/MongooseIM, pull requests merged in 2019-06, with the labels that each got.

#2320 Add sender_id to mam_muc_message RDBMS table
  big_tests/tests/gdpr_SUITE.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/muc_SUITE.erl
  doc/migrations/3.3.0_3.3.0plus.md
  mkdocs.yml
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_muc_rdbms_arch.erl
  src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_rdbms_user.erl
  test/mod_mam_meta_SUITE.erl
Labels: GDPR, WIP :construction:, waiting-for-ci

#2315 Add conflict_behaviour=kick_old for ejabberd_service
  big_tests/tests/component_SUITE.erl
  big_tests/tests/component_helper.erl
  doc/advanced-configuration/Listener-modules.md
  rel/mim1.vars.config
  src/ejabberd_service.erl
  src/mongoose_packet_handler.erl
Labels: waiting-for-review

#2336 GDPR data retrival for mod_mam_muc @ Riak DBMS
  big_tests/tests/gdpr_SUITE.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  tools/mam_search_schema.xml
Labels: MAM, waiting-for-review

#2337 Escalus update before the release
  big_tests/rebar.config
  big_tests/rebar.lock
Labels: WIP :construction:, waiting-for-ci

#2328 Removal of personal data from mod_mam
  big_tests/tests/gdpr_SUITE.erl
  src/gdpr.erl
  src/mam/ejabberd_gen_mam_archive.erl
  src/mam/ejabberd_gen_mam_prefs.erl
  src/mam/mod_mam.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_cassandra_prefs.erl
  src/mam/mod_mam_elasticsearch_arch.erl
  src/mam/mod_mam_mnesia_prefs.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_rdbms_async_pool_writer.erl
  src/mam/mod_mam_rdbms_prefs.erl
  src/mam/mod_mam_rdbms_user.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/pubsub/mod_pubsub.erl
Labels: waiting-for-review

#2346 Add known issues for rel 3.4.0 to docs
  doc/advanced-configuration/database-backends-configuration.md
  doc/advanced-configuration/outgoing-connections.md
  doc/developers-guide/Testing-MongooseIM.md
  doc/operation-and-maintenance/known-issues.md
  mkdocs.yml
Labels: doc, waiting-for-review

#2349 Add GDPR removal for pubsub (alternative)
  big_tests/tests/gdpr_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  src/pubsub/gen_pubsub_node.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/mod_pubsub_db_mnesia.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/mod_pubsub_db_rdbms_sql.erl
  src/pubsub/node_flat.erl
  src/pubsub/node_pep.erl
  src/pubsub/node_push.erl
  src/pubsub/pubsub_index.erl
Labels: waiting-for-review

#2352 Release 3.4.0
  .travis.yml
  CHANGELOG.md
  README.md
  VERSION
  doc/index.md
  doc/migrations/3.3.0_3.4.0.md
  mkdocs.yml
Labels: waiting-for-ci
