Repository esl/MongooseIM, pull requests merged in 2019-12, with the labels that each got.

#2547 Resort to standard otp base64 module in jlib
  src/jlib.erl
Labels: ready, waiting-for-review

#2553 Eradicate mod_push
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_integration_SUITE.erl
  doc/migrations/3.5.0_3.5.0plus.md
  src/mod_push.erl
Labels: waiting-for-review

#2554 PubSub-less push notifications
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_integration_SUITE.erl
  doc/modules/mod_event_pusher_push.md
  src/event_pusher/mod_event_pusher_push.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/gen_mod.erl
Labels: WIP :construction:

#2569 Push priority configurable by node
  big_tests/tests/push_integration_SUITE.erl
  doc/user-guide/Push-notifications.md
  src/mod_push_service_mongoosepush.erl
Labels: waiting-for-ci, waiting-for-review

#2544 Move logic from jid:from_binary into a nif
  c_src/jid.cpp
  rebar.config
  src/jid.erl
  test/jid_SUITE.erl
Labels: load tests, nifs, ready, waiting-for-review
