Repository esl/MongooseIM, pull requests merged in 2019-01, with the labels that each got.

#2183 Fix broken or remove outdated links in docs
  README.md
  doc/Basic-configuration.md
  doc/Roadmap.md
  doc/advanced-configuration/Listener-modules.md
  doc/advanced-configuration/Modules.md
  doc/developers-guide/xep_tool.md
  doc/modules/mod_bosh.md
  doc/open-extensions/token-reconnection.md
  doc/user-guide/Features-and-supported-standards.md
  doc/user-guide/ICE_tutorial.md
  doc/user-guide/ICE_tutorial/mangosta_ice_settings.png
  doc/user-guide/ICE_tutorial/mangosta_ice_settings_1.png
  doc/user-guide/ICE_tutorial/mangosta_ice_settings_2.png
  doc/user-guide/ICE_tutorial/mangosta_ice_settings_3.png
  doc/user-guide/ICE_tutorial/mangosta_login.png
  doc/user-guide/ICE_tutorial/mangosta_start_stream.png
  doc/user-guide/ICE_tutorial/mangosta_start_stream_1.png
  doc/user-guide/ICE_tutorial/mangosta_start_stream_2.png
  doc/user-guide/ICE_tutorial/mangosta_start_stream_3.png
  doc/user-guide/release_config.md
  mkdocs.yml
Labels: doc, waiting-for-review

#2166 Return MAM item-not-found IQ result when a nonexistent message ID is asked for
  big_tests/tests/mam_SUITE.erl
  src/mam/mod_mam.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_elasticsearch_arch.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_muc_cassandra_arch.erl
  src/mam/mod_mam_muc_elasticsearch_arch.erl
  src/mam/mod_mam_muc_rdbms_arch.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mam/mod_mam_utils.erl
Labels: WIP :construction:

#2153 Upsert helper
  include/mod_inbox.hrl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_rdbms_mssql.erl
  src/inbox/mod_inbox_rdbms_mysql.erl
  src/inbox/mod_inbox_rdbms_pgsql.erl
  src/inbox/mod_inbox_utils.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_cache.erl
  src/pubsub/mod_pubsub_cache_mnesia.erl
  src/pubsub/mod_pubsub_cache_rdbms.erl
  src/pubsub/mod_pubsub_db_rdbms.erl
  src/pubsub/mod_pubsub_db_rdbms_sql.erl
  src/rdbms/mongoose_rdbms.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/rdbms_queries.erl
Labels: waiting-for-ci, waiting-for-review

#2203 Upgrade fast_tls and exml to versions that use port_compiler
  rebar.config
  rebar.lock
Labels: waiting-for-review
