Repository esl/MongooseIM, pull requests merged in 2019-09, with the labels that each got.

#2354 Fix user disco#info when rooms_in_rosters enabled
  big_tests/tests/muc_light_SUITE.erl
  src/mod_disco.erl
Labels: community

#2426 Filter REST commands by subcategory as well
  big_tests/tests/rest_SUITE.erl
  src/mongoose_api_admin.erl
  src/mongoose_api_client.erl
  src/mongoose_commands.erl
Labels: waiting-for-ci, waiting-for-review

#2435 Remove best-effort GDPR retrieve and remove
  big_tests/tests/gdpr_SUITE.erl
  doc/Advanced-configuration.md
  doc/advanced-configuration/Services.md
  doc/operation-and-maintenance/gdpr-considerations.md
  doc/operation-and-maintenance/known-issues.md
  mkdocs.yml
  rel/files/mongooseim.cfg
  rel/files/mongooseim.cfg.token-support
  src/admin_extra/service_admin_extra.erl
  src/admin_extra/service_admin_extra_gdpr.erl
  src/auth/ejabberd_auth.erl
  src/ejabberd_app.erl
  src/ejabberd_hooks.erl
  src/gdpr.erl
  src/inbox/mod_inbox.erl
  src/mam/ejabberd_gen_mam_archive.erl
  src/mam/ejabberd_gen_mam_prefs.erl
  src/mam/mod_mam.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_cassandra_prefs.erl
  src/mam/mod_mam_elasticsearch_arch.erl
  src/mam/mod_mam_mnesia_prefs.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_muc_cassandra_arch.erl
  src/mam/mod_mam_muc_elasticsearch_arch.erl
  src/mam/mod_mam_muc_rdbms_arch.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_rdbms_prefs.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mod_offline.erl
  src/mod_privacy.erl
  src/mod_private.erl
  src/mod_roster.erl
  src/mod_vcard.erl
  src/mongoose_lib.erl
  src/pubsub/gen_pubsub_node.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/node_flat.erl
  src/service_cache.erl
Labels: waiting-for-review

#2439 Switch Docker image build to CircleCI
  .circleci/config.yml
  .travis.yml
  tools/build-releases.sh
  tools/circle-build-and-push-docker.sh
Labels: waiting-for-ci, waiting-for-review

#2436 [skip ci] Language check for GDPR docs
  doc/operation-and-maintenance/gdpr-considerations.md
Labels: doc

#2447 Fixes for CircleCI
  .circleci/config.yml
Labels: WIP :construction:

#2437 mod_global_distrib_SUITE: ignore known failure, fail otherwise
  big_tests/tests/mod_global_distrib_SUITE.erl
Labels: global distribution, waiting-for-review

#2271 Fix chat marker archiving in MUC
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mam_helper.hrl
  big_tests/tests/muc_light_helper.erl
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_muc.erl
Labels: waiting-for-ci, waiting-for-review

#2453 Fix case when two initial presences are received after reconnection in sm:resume_session_state_stop_c2s
  big_tests/tests/sm_SUITE.erl
  src/ejabberd_c2s.erl
Labels: ci-errors

#2455 mod_event_pusher_rabbit quickfix
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
Labels: ci-errors

#2459 Improve setup db script
  priv/mssql2012.sql
  tools/setup-mssql-database.sh
  tools/setup-redis.sh
  tools/setup_riak
  tools/setup_riak.escript
  tools/ssl/Makefile
  tools/travis-common-vars.sh
  tools/travis-setup-db.sh
  tools/travis-setup-ldap.sh
  tools/wait_for_service.sh
Labels: waiting-for-review

#2466 Deprecate MAM 0.3
  doc/modules/mod_mam.md
  src/mam/mod_mam_utils.erl
Labels: waiting-for-ci, waiting-for-review

#2454 Ensure that process is stopped in mod_global_distrib_SUITE:test_pm_with_graceful_reconnection_to_different_server
  big_tests/test.config
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mongoose_helper.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
Labels: ci-errors, ready

#2469 Wait for solr to be up
  tools/travis-setup-db.sh
Labels: ready

#2465 Deprecate OTPs older than 21.2
  doc/developers-guide/OpenSSL-and-FIPS.md
  doc/modules/mod_jingle_sip.md
  doc/operation-and-maintenance/known-issues.md
  doc/user-guide/How-to-build.md
  rebar.config
  src/ejabberd_app.erl
Labels: waiting-for-ci, waiting-for-review

#2423 Remove XMLNS strip in ejabberd_c2s
  big_tests/tests/inbox_helper.erl
  src/ejabberd_c2s.erl
Labels: ready

#2470 Use transactions for mongoose_cluster operations
  big_tests/tests/cluster_commands_SUITE.erl
  big_tests/tests/distributed_helper.erl
  src/mongoose_cluster.erl
Labels: waiting-for-review

#2474 Ensure that Mnesia table exist in ejabberdctl_SUITE before starting test
  big_tests/tests/ejabberdctl_SUITE.erl
Labels: ci-errors, waiting-for-review

#2247 fix docs about mongoose_api_admin authorization
  doc/advanced-configuration/Listener-modules.md
Labels: community, doc, waiting-for-review

#2478 Fix rdbms typo
  CHANGELOG.md
  doc/Advanced-configuration.md
  doc/operation-and-maintenance/Mongoose-metrics.md
Labels: doc

#2475 Configure ports using test.config
  .gitignore
  big_tests/run_common_test.erl
  big_tests/test.config
  big_tests/tests/component_SUITE.erl
  big_tests/tests/component_helper.erl
  big_tests/tests/connect_SUITE.erl
  big_tests/tests/ejabberd_node_utils.erl
  big_tests/tests/metrics_api_SUITE.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mod_http_notification_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/push_http_SUITE.erl
  big_tests/tests/reload_helper.erl
  big_tests/tests/rest_client_SUITE.erl
  big_tests/tests/s2s_SUITE.erl
  big_tests/tests/s2s_helper.erl
  big_tests/tests/sasl_external_SUITE.erl
  doc/Basic-configuration.md
  rel/fed1.vars.config
  rel/files/mongooseim.cfg
  rel/mim1.vars.config
  rel/mim2.vars.config
  rel/mim3.vars.config
  rel/reg1.vars.config
  rel/vars.config.in
  src/global_distrib/mod_global_distrib_receiver.erl
  src/global_distrib/mod_global_distrib_utils.erl
  tools/test_runner/apply_templates.erl
Labels: waiting-for-review
