Repository esl/MongooseIM, pull requests merged in 2019-11, with the labels that each got.

#2523 Create mogoose user stats prototype
  big_tests/default.spec
  big_tests/tests/mongoose_user_stats_SUITE.erl
  rel/fed1.vars.config
  rel/files/mongooseim.cfg
  rel/mim1.vars.config
  rel/mim2.vars.config
  rel/mim3.vars.config
  rel/reg1.vars.config
  rel/vars.config.in
  src/config/mongoose_config_parser.erl
  src/ejabberd_app.erl
  src/mongoose_user_stats.erl
Labels: waiting-for-review

#2158 Do not recreate accumulator when sending out a stanza
  src/ejabberd_c2s.erl
Labels: WIP :construction:

#2529 [skip ci] Fix small documentation errors
  doc/modules/mod_event_pusher_http.md
  doc/modules/mod_offline.md
Labels: doc

#2536 Better MUC light room config
  big_tests/tests/muc_light_SUITE.erl
  doc/migrations/3.5.0_3.5.0plus.md
  doc/modules/mod_muc_light.md
  doc/operation-and-maintenance/known-issues.md
  include/mod_muc_light.hrl
  mkdocs.yml
  src/muc_light/mod_muc_light.erl
  src/muc_light/mod_muc_light_codec_legacy.erl
  src/muc_light/mod_muc_light_codec_modern.erl
  src/muc_light/mod_muc_light_db.erl
  src/muc_light/mod_muc_light_db_mnesia.erl
  src/muc_light/mod_muc_light_db_rdbms.erl
  src/muc_light/mod_muc_light_room.erl
  src/muc_light/mod_muc_light_room_config.erl
  src/muc_light/mod_muc_light_utils.erl
  test/muc_light_SUITE.erl
Labels: waiting-for-review
