Repository esl/MongooseIM, pull requests merged in 2019-03, with the labels that each got.

#2225 Update find-hooks.awk
  doc/developers-guide/Hooks-and-handlers.md
  doc/developers-guide/hooks_description.md
  tools/find-hooks.awk
Labels: waiting-for-review

#2216 Fix starting rabbit pool if no options are passed
  big_tests/tests/mod_event_pusher_rabbit_SUITE.erl
  src/mongoose_amqp.erl
  src/wpool/mongoose_wpool_rabbit.erl
Labels: bug, waiting-for-review

#2233 [skip ci] updated http auth documentation
  doc/authentication-backends/HTTP-authentication-module.md
Labels: doc, waiting-for-review

#2227 [skip ci] Update docs for 3.3.0
  doc/authentication-backends/PKI-authentication-module.md
  doc/authentication-methods/client-certificate.md
  doc/developers-guide/hooks_description.md
  doc/developers-guide/mod_muc_light_developers_guide.md
  doc/modules/mod_http_upload.md
  doc/modules/mod_last.md
  doc/modules/mod_mam.md
  doc/modules/mod_muc_light.md
  doc/modules/mod_offline.md
  doc/modules/mod_privacy.md
  doc/modules/mod_private.md
  doc/modules/mod_pubsub.md
  doc/modules/mod_roster.md
  doc/modules/mod_vcard.md
  doc/operation-and-maintenance/Mongoose-metrics.md
Labels: waiting-for-review

#2224 Use new Escalus
  big_tests/rebar.config
Labels: waiting-for-review

#2231 Configuration of cyrsasl_external
  big_tests/tests/sasl_external_SUITE.erl
  doc/authentication-methods/client-certificate.md
  rel/files/mongooseim.cfg
  rel/vars.config.in
  src/sasl/cyrsasl_external.erl
Labels: waiting-for-review

#2054 Wait longer for replaced c2s
  big_tests/tests/connect_SUITE.erl
  big_tests/tests/lager_ct_backend.erl
  big_tests/tests/mod_aws_sns_SUITE.erl
  big_tests/tests/mod_global_distrib_SUITE.erl
  big_tests/tests/mongoose_cassandra_SUITE.erl
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_pubsub_SUITE.erl
  big_tests/tests/race_conditions_SUITE.erl
  big_tests/tests/sasl_SUITE.erl
  big_tests/tests/sm_SUITE.erl
  doc/Advanced-configuration.md
  include/ejabberd_c2s.hrl
  src/ejabberd_c2s.erl
Labels: waiting-for-review

#2049 Fix 3 issues in SM resumption
  big_tests/tests/sm_SUITE.erl
  include/ejabberd_c2s.hrl
  src/ejabberd_c2s.erl
  src/jlib.erl
Labels: waiting-for-review

#2238 Disco items offline rooms fix
  big_tests/tests/muc_SUITE.erl
  src/mod_muc.erl
Labels: waiting-for-review
