Repository esl/MongooseIM, pull requests merged in 2019-04, with the labels that each got.

#2254 Get rid of store_type/1 in auth backends
  big_tests/tests/login_SUITE.erl
  big_tests/tests/oauth_SUITE.erl
  doc/Advanced-configuration.md
  doc/authentication-methods/client-certificate.md
  src/auth/ejabberd_auth.erl
  src/auth/ejabberd_auth_anonymous.erl
  src/auth/ejabberd_auth_external.erl
  src/auth/ejabberd_auth_http.erl
  src/auth/ejabberd_auth_internal.erl
  src/auth/ejabberd_auth_jwt.erl
  src/auth/ejabberd_auth_ldap.erl
  src/auth/ejabberd_auth_pki.erl
  src/auth/ejabberd_auth_rdbms.erl
  src/auth/ejabberd_auth_riak.erl
  src/auth/ejabberd_gen_auth.erl
  src/sasl/cyrsasl.erl
  src/sasl/cyrsasl_external.erl
  test/auth_external_SUITE.erl
  test/auth_http_SUITE.erl
  test/auth_jwt_SUITE.erl
Labels: waiting-for-review

#2220 Remove the empty 'to' attribute from archived MUC messages
  big_tests/tests/mam_SUITE.erl
  src/jlib.erl
  src/mam/mod_mam_muc.erl
Labels: waiting-for-review

#2252 Fix xeplist Makefile rule and xep_tool escript
  Makefile
  tools/xep_tool/xep_tool.escript
Labels: XEPs, waiting-for-review

#2261 Update inconsistent PubSub cache doc
  doc/modules/mod_pubsub.md
Labels: doc, waiting-for-review

#2260 gdpr logs collection
  big_tests/tests/gdpr_SUITE.erl
  priv/parse_logs.sh
  src/admin_extra/service_admin_extra_gdpr.erl
  src/ejabberd_config.erl
  src/ejabberd_ctl.erl
  src/ejabberd_loglevel.erl
Labels: GDPR, waiting-for-ci, waiting-for-review

#2262 Register command with automatic jid creation
  big_tests/tests/ejabberdctl_SUITE.erl
  doc/user-guide/Getting-started.md
  doc/user-guide/ICE_tutorial.md
  doc/user-guide/Jingle-SIP-setup.md
  src/ejabberd_admin.erl
Labels: GDPR, waiting-for-ci, waiting-for-review
