Repository esl/MongooseIM, pull requests merged in 2019-10, with the labels that each got.

#2472 SM/update_return_old_h
  big_tests/tests/sm_SUITE.erl
  doc/modules/mod_stream_management.md
  rel/files/mongooseim.cfg
  src/ejabberd_c2s.erl
  src/ejabberd_sm.erl
  src/ejabberd_sm_mnesia.erl
  src/ejabberd_sm_redis.erl
  src/mod_stream_management.erl
  src/mongoose_client_api_sse.erl
  src/stream_management/stream_management_stale_h.erl
  test/ejabberd_c2s_SUITE_mocks.erl
  test/ejabberd_sm_SUITE.erl
  test/mongoose_cleanup_SUITE.erl
Labels: ready, stream management, waiting-for-review

#2481 Fix inbox unread count retrieval for push notifications
  big_tests/tests/push_integration_SUITE.erl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_utils.erl
Labels: waiting-for-ci, waiting-for-review

#2486 Curate ct_helper:repeat_all_until_all_ok
  big_tests/test.config
  big_tests/tests/ct_helper.erl
Labels: waiting-for-ci, waiting-for-review

#2489 [skip ci] Make sure it stays in one line
  doc/operation-and-maintenance/Mongoose-metrics.md
Labels: ready

#2492 Better error reporting for tools/travis-upload-to-gdrive.sh
  .travis.yml
  tools/travis-upload-to-gdrive.sh
Labels: Hacktoberfest, waiting-for-review

#2482 Disabled stream mgmt crashes
  big_tests/tests/sm_SUITE.erl
  src/ejabberd_c2s.erl
  test/ejabberd_c2s_SUITE_mocks.erl
Labels: bug, stream management, waiting-for-review

#2494 To hell with get_stacktrace!
  big_tests/run_common_test.erl
  big_tests/src/ct_markdown_errors_hook.erl
  big_tests/tests/gdpr_SUITE.erl
  big_tests/tests/inbox_helper.erl
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  doc/developers-guide/logging.md
  rebar.config
  rebar.lock
  src/auth/ejabberd_auth_rdbms.erl
  src/cert_utils.erl
  src/ejabberd_admin.erl
  src/ejabberd_config.erl
  src/ejabberd_ctl.erl
  src/ejabberd_local.erl
  src/ejabberd_router.erl
  src/ejabberd_sm.erl
  src/event_pusher/mod_event_pusher_sns.erl
  src/gen_iq_handler.erl
  src/gen_mod.erl
  src/global_distrib/mod_global_distrib_connection.erl
  src/jingle_sip/jingle_sip_callbacks.erl
  src/jingle_sip/mod_jingle_sip.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_cassandra_prefs.erl
  src/mam/mod_mam_muc_cassandra_arch.erl
  src/mam/mod_mam_muc_rdbms_arch.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mod_auth_token.erl
  src/mod_cowboy.erl
  src/mod_offline_riak.erl
  src/mod_privacy_rdbms.erl
  src/mod_roster.erl
  src/mod_roster_rdbms.erl
  src/mod_vcard.erl
  src/mongoose_api_admin.erl
  src/mongoose_api_common.erl
  src/mongoose_commands.erl
  src/mongoose_iq.erl
  src/mongoose_service.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_db.erl
  src/pubsub/pubsub_form_utils.erl
  src/rdbms/mongoose_rdbms.erl
  src/safely.erl
  src/wpool/mongoose_wpool.erl
  tools/migration/sender-jid-from-mam-message.escript
  tools/setup_riak.escript
  tools/test_runner/complete_test_name.erl
Labels: waiting-for-review

#2304 Hide service name option
  big_tests/tests/connect_SUITE.erl
  doc/Advanced-configuration.md
  src/ejabberd_c2s.erl
Labels: waiting-for-ci, waiting-for-review

#2498 Replace p1_time_compat with direct OTP functions
  load_test/amoc_scenarios/xmpp_amqp.erl
  src/admin_extra/service_admin_extra_accounts.erl
  src/auth/ejabberd_auth_external.erl
  src/auth/ejabberd_auth_riak.erl
  src/ejabberd_c2s.erl
  src/ejabberd_config.erl
  src/ejabberd_s2s_out.erl
  src/gen_iq_handler.erl
  src/global_distrib/mod_global_distrib_bounce.erl
  src/global_distrib/mod_global_distrib_connection.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/global_distrib/mod_global_distrib_receiver.erl
  src/global_distrib/mod_global_distrib_worker.erl
  src/jingle_sip/mod_jingle_sip_backend.erl
  src/mam/mam_iq.erl
  src/mam/mod_mam_utils.erl
  src/mod_bosh_socket.erl
  src/mod_commands.erl
  src/mod_last.erl
  src/mod_muc.erl
  src/mod_muc_log.erl
  src/mod_offline.erl
  src/mod_offline_mnesia.erl
  src/mod_offline_rdbms.erl
  src/mod_register.erl
  src/mod_time.erl
  src/mongoose_client_api_messages.erl
  src/mongoose_client_api_rooms_messages.erl
  src/rdbms/mongoose_rdbms.erl
  src/sasl/cyrsasl_anonymous.erl
  src/shaper.erl
  src/shaper_srv.erl
  src/stream_management/stream_management_stale_h.erl
  test/auth_jwt_SUITE.erl
  test/ejabberd_sm_SUITE.erl
Labels: waiting-for-review

#2274 Add chat markers support to room REST API
  big_tests/tests/rest_client_SUITE.erl
  big_tests/tests/rest_helper.erl
  doc/rest-api/Client-frontend_swagger.yml
  src/mongoose_client_api_rooms_messages.erl
Labels: waiting-for-ci, waiting-for-review

#2490 Configurable riak buckets
  doc/Advanced-configuration.md
  doc/authentication-backends/Riak-authentication-module.md
  doc/modules/mod_last.md
  doc/modules/mod_mam.md
  doc/modules/mod_offline.md
  doc/modules/mod_privacy.md
  doc/modules/mod_private.md
  doc/modules/mod_roster.md
  doc/modules/mod_vcard.md
  mkdocs.yml
  src/auth/ejabberd_auth_riak.erl
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mod_last_riak.erl
  src/mod_offline_riak.erl
  src/mod_privacy_riak.erl
  src/mod_private_riak.erl
  src/mod_roster_riak.erl
  src/mod_vcard_riak.erl
Labels: Hacktoberfest, waiting-for-review

#2243 Handle available_worker incompatibility
  doc/advanced-configuration/outgoing-connections.md
  src/wpool/mongoose_wpool.erl
  src/wpool/mongoose_wpool_redis.erl
  src/wpool/mongoose_wpool_riak.erl
  test/mongoose_wpool_SUITE.erl
Labels: waiting-for-review

#2501 Actually cache gdrive script on Travis
  .travis.yml
  tools/travis-upload-to-gdrive.sh
Labels: Hacktoberfest, waiting-for-review

#2499 Rewrite parallel helper for mam_SUITE
  big_tests/tests/mam_SUITE.erl
Labels: Hacktoberfest, tests, waiting-for-review

#2493 Add setup_schemas and setup_indexes into tools/setup_riak.escript
  tools/setup_riak.escript
  tools/travis-setup-db.sh
Labels: Hacktoberfest, waiting-for-review

#2504 Add and use muc_helper:story_with_room/4
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_helper.erl
Labels: waiting-for-review

#2512 Fix pruning in stream_management_stale_h
  src/stream_management/stream_management_stale_h.erl
Labels: waiting-for-review

#2502 Workaround transport delivery problems
  big_tests/tests/sm_SUITE.erl
  src/ejabberd_receiver.erl
Labels: Hacktoberfest, waiting-for-review

#2514 Add a clarification about session replacement to docs
  doc/user-guide/Features-and-supported-standards.md
  doc/user-guide/Getting-started.md
Labels: doc, waiting-for-review

#2283 Add dummy auth module
  doc/authentication-backends/Dummy-authentication-module.md
  mkdocs.yml
  src/auth/ejabberd_auth_dummy.erl
  test/auth_dummy_SUITE.erl
Labels: waiting-for-review
