Repository esl/MongooseIM, pull requests merged in 2019-08, with the labels that each got.

#2390 Fix hiding error with empty list []
  src/pubsub/mod_pubsub_db_mnesia.erl
Labels: bug, refactoring, tests, waiting-for-ci, waiting-for-review

#2377 Deprecate TLS older than 1.2
  big_tests/tests/connect_SUITE.erl
  doc/Advanced-configuration.md
  doc/advanced-configuration/Listener-modules.md
  doc/advanced-configuration/TLS-hardening.md
  doc/modules/mod_global_distrib.md
  doc/user-guide/ICE_tutorial/mongooseim.cfg
  mkdocs.yml
  rel/fed1.vars.config
  rel/files/app.config
  rel/files/mongooseim.cfg
  rel/files/mongooseim.cfg.token-support
  rel/mim2.vars.config
  rel/mim3.vars.config
  rel/reg1.vars.config
  src/ejabberd_socket.erl
  src/ejabberd_tls.erl
  src/global_distrib/mod_global_distrib_transport.erl
  test/cowboy_SUITE_data/mongooseim.onlyhttp.cfg
  test/cowboy_SUITE_data/mongooseim.onlyws.cfg
  test/ejabberd_config_SUITE_data/mongooseim.default.cfg
  test/ejabberd_config_SUITE_data/mongooseim.split.cfg
  test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.cfg
  test/ejabberd_config_SUITE_data/mongooseim.with_mod_offline.different_opts.cfg
  test/revproxy_SUITE_data/mongooseim.norules.cfg
  test/revproxy_SUITE_data/mongooseim.onerule.cfg
Labels: waiting-for-review

#2408 Compile cover once
  big_tests/run_common_test.erl
  rebar.config
Labels: waiting-for-review

#2407 Use rsync and template generation to make other dev releases
  .circleci/config.yml
  .travis.yml
  Makefile
  rebar.config
  tools/build-releases.sh
  tools/test_runner/apply_templates.erl
  tools/test_runner/apply_templates.sh
Labels: waiting-for-review

#2397 Use riak from repo to speed up compilation
  rebar.config
  rebar.lock
Labels: waiting-for-review

#2400 Reduce memory usage for dev MongooseIM VMs
  rel/fed1.vars.config
  rel/files/vm.args
  rel/mim1.vars.config
  rel/mim2.vars.config
  rel/mim3.vars.config
  rel/reg1.vars.config
  rel/vars.config.in
Labels: waiting-for-review

#2399 Improve ct_markdown_errors hook
  big_tests/src/ct_markdown_errors_hook.erl
  tools/travis-test.sh
Labels: waiting-for-review

#2398 Fix error handling in silent_exec when VERBOSE=1
  tools/silent_exec.sh
Labels: waiting-for-review

#2403 Properly detect that redis is not running in ejabberd_sm_SUITE
  test/ejabberd_sm_SUITE.erl
Labels: waiting-for-review

#2409 Improve mongoose control script
  rel/files/mongooseim
  rel/files/mongooseimctl
  src/ejabberd.erl
  src/ejabberd_app.erl
  tools/start-nodes.sh
  tools/stop-nodes.sh
Labels: waiting-for-review

#2404 Fix undefined pid error in dead_pool_is_restarted
  test/mongoose_wpool_SUITE.erl
Labels: waiting-for-review

#2411 Cache built deps
  .travis.yml
  tools/cache-build.sh
  tools/cache-certs.sh
  tools/cache-tests.sh
Labels: waiting-for-review

#2418 Pull database images in parallel with compiling on Travis
  .travis.yml
  tools/travis-pull-db.sh
Labels: waiting-for-review

#2421 Update OTP versions matrix for Travis and CircleCI
  .circleci/config.yml
  .travis.yml
  tools/test-runner.sh
Labels: waiting-for-ci, waiting-for-review

#2424 Fix .travis.yml to execute small tests both on OTP 22 and 21
  .travis.yml
Labels: waiting-for-ci, waiting-for-review
