Repository esl/MongooseIM, pull requests merged in 2020-01, with the labels that each got.

#2581 Async thread pool not used anymore
  rel/files/vm.args
Labels: ready

#2582 Cleaning code
  big_tests/tests/mam_helper.erl
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/push_helper.erl
  big_tests/tests/rest_helper.erl
  big_tests/tests/sm_SUITE.erl
  src/admin_extra/service_admin_extra_accounts.erl
  src/admin_extra/service_admin_extra_roster.erl
  src/admin_extra/service_admin_extra_sessions.erl
  src/admin_extra/service_admin_extra_stanza.erl
  src/amp_strategy.erl
  src/auth/ejabberd_auth.erl
  src/auth/ejabberd_auth_external.erl
  src/cassandra/mongoose_cassandra.erl
  src/ejabberd_c2s.erl
  src/ejabberd_local.erl
  src/ejabberd_sm.erl
  src/event_pusher/mod_event_pusher_hook_translator.erl
  src/event_pusher/mod_event_pusher_push.erl
  src/event_pusher/mod_event_pusher_rabbit.erl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_utils.erl
  src/jingle_sip/jingle_sip_callbacks.erl
  src/jingle_sip/mod_jingle_sip.erl
  src/mod_carboncopy.erl
  src/mod_disco.erl
  src/mod_last.erl
  src/mod_muc_room.erl
  src/mod_ping.erl
  src/mod_register.erl
  src/mod_roster.erl
  src/mod_sic.erl
  src/mongoose_client_api/mongoose_client_api_sse.erl
  src/mongoose_deprecations.erl
  src/offline/mod_offline_riak.erl
  src/pubsub/mod_pubsub.erl
  src/pubsub/mod_pubsub_cache_rdbms.erl
  src/sasl/cyrsasl_plain.erl
  test/ejabberd_c2s_SUITE_mocks.erl
  test/ejabberd_sm_SUITE.erl
  test/mongoose_cleanup_SUITE.erl
Labels: ready, waiting-for-review

#2577 Test pubsub tools cleanup
  big_tests/tests/gdpr_SUITE.erl
  big_tests/tests/pubsub_SUITE.erl
  big_tests/tests/pubsub_s2s_SUITE.erl
  big_tests/tests/pubsub_tools.erl
  big_tests/tests/push_SUITE.erl
  big_tests/tests/push_integration_SUITE.erl
  big_tests/tests/push_pubsub_SUITE.erl
Labels: ready, waiting-for-review

#2599 [Small] Modernise time functionality for mod_last
  doc/developers-guide/flat_options.md
  src/ejabberd_config.erl
  src/mod_last.erl
Labels: ready, waiting-for-review

#2601 Sysmetrics/log transparency
  big_tests/tests/lager_ct_backend.erl
  big_tests/tests/service_mongoose_system_metrics_SUITE.erl
  rel/mim3.vars.config
  src/ejabberd_app.erl
  src/mongoose_service.erl
  src/system_metrics/service_mongoose_system_metrics.erl
Labels: system metrics, waiting-for-review

#2272 Advertise MAM in disco#info
  big_tests/tests/mam_helper.erl
  big_tests/tests/muc_SUITE.erl
  big_tests/tests/muc_helper.erl
  big_tests/tests/muc_light_SUITE.erl
  big_tests/tests/muc_light_legacy_SUITE.erl
  src/mod_muc.erl
  src/mod_muc_room.erl
  src/muc_light/mod_muc_light_codec_legacy.erl
  src/muc_light/mod_muc_light_codec_modern.erl
Labels: WIP :construction:, community

#2044 cert auth. support for ejabberd_auth_http
  big_tests/tests/sasl_external_SUITE.erl
  doc/authentication-backends/HTTP-authentication-module.md
  doc/authentication-methods/client-certificate.md
  src/auth/ejabberd_auth_http.erl
  src/sasl/cyrsasl_external.erl
  src/sasl/cyrsasl_external_verification.erl
  test/auth_http_SUITE.erl
  test/mim_ct_rest.erl
  test/mim_ct_rest_handler.erl
Labels: waiting-for-review

#2605 This file has not been needed in ages!
  c_src/stdint.h
Labels: ready

#2614 [skip ci] add cluster ID to migration script
  doc/migrations/3.5.0_3.5.0plus.md
Labels: ready

#2611 Docs/push notifications
  README.md
  doc/modules/mod_event_pusher.md
  doc/modules/mod_event_pusher_push.md
  doc/user-guide/Features-and-supported-standards.md
  doc/user-guide/Push-notifications.md
  doc/user-guide/PushNotificationscomponents.png
  doc/user-guide/push-notifications/Push-notifications-client-side.md
  doc/user-guide/push-notifications/Push-notifications.md
  doc/user-guide/push-notifications/PushNotifications-MIM_with_local_pubsub.png
  doc/user-guide/push-notifications/PushNotifications-XEP-overview.png
  doc/user-guide/push-notifications/PushNotifications-no_pubsub.png
  doc/user-guide/push-notifications/With-MongoosePush.md
  doc/user-guide/push-notifications/component-architecture-with-PubSub.png
  doc/user-guide/push-notifications/component-architecture-without-PubSub.png
  doc/user-guide/push-notifications/pubsub_full_push_notifications_example_message_flow.png
  doc/user-guide/push-notifications/pubsub_less_push_notifications_example_message_flow.png
  doc/user-guide/push_notifications_example_message_flow.png
  mkdocs.yml
  src/event_pusher/mod_event_pusher_push_plugin.erl
Labels: doc, waiting-for-review
