Repository esl/MongooseIM, pull requests merged in 2020-11, with the labels that each got.

#2924 Reduce execution time by 20% for simple prepared queries in postgres
  src/rdbms/mongoose_rdbms_pgsql.erl
Labels: waiting-for-review

#2922 Reduce stringprepping for roster modules
  include/mod_roster.hrl
  src/admin_extra/service_admin_extra_roster.erl
  src/auth/ejabberd_auth.erl
  src/mod_commands.erl
  src/mod_roster.erl
  src/mongoose_client_api/mongoose_client_api_contacts.erl
  src/muc_light/mod_muc_light.erl
  test/roster_SUITE.erl
Labels: hacktoberfest-accepted

#2934 TLS and Ubuntu
  big_tests/tests/connect_SUITE.erl
  tools/ssl/Makefile
Labels: ready, waiting-for-review

#2947 Load nksip in parallel with big timeouts
  big_tests/tests/dynamic_modules.erl
  big_tests/tests/jingle_SUITE.erl
Labels: ci-errors
