Repository esl/MongooseIM, pull requests merged in 2020-03, with the labels that each got.

#2651 Make s2s use hooks wrapper
  src/ejabberd_s2s.erl
  src/ejabberd_s2s_in.erl
  src/ejabberd_s2s_out.erl
  src/mongoose_hooks.erl
Labels: ready

#2525 Update exported flags in How to compile MIM docs
  doc/user-guide/How-to-build.md
Labels: WIP :construction:, doc

#2654 Add `jid` as an external library
  big_tests/rebar.config
  big_tests/rebar.lock
  big_tests/run_common_test.erl
  big_tests/src/ejabberd_tests.app.src
  big_tests/tests/mongoose_helper.erl
  c_src/jid.cpp
  include/jid.hrl
  include/jlib.hrl
  rebar.config
  rebar.lock
  src/auth/ejabberd_auth_jwt.erl
  src/event_pusher/mod_event_pusher_push_rdbms.erl
  src/global_distrib/mod_global_distrib_mapping_redis.erl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_muclight.erl
  src/jid.erl
  src/mam/mod_mam_utils.erl
  src/mod_vcard.erl
  src/mod_vcard_ldap.erl
  src/mod_vcard_mnesia.erl
  src/mod_vcard_rdbms.erl
  src/mod_vcard_riak.erl
  src/mod_websockets.erl
  src/mongooseim.app.src
  src/sasl/cyrsasl_digest.erl
  src/sasl/cyrsasl_external_verification.erl
  test/acc_SUITE.erl
  test/acl_SUITE.erl
  test/auth_dummy_SUITE.erl
  test/auth_external_SUITE.erl
  test/auth_http_SUITE.erl
  test/auth_jwt_SUITE.erl
  test/auth_tokens_SUITE.erl
  test/commands_SUITE.erl
  test/commands_backend_SUITE.erl
  test/component_reg_SUITE.erl
  test/ejabberd_c2s_SUITE.erl
  test/ejabberd_config_SUITE.erl
  test/ejabberd_sm_SUITE.erl
  test/jid_SUITE.erl
  test/jid_gen.erl
  test/jlib_SUITE.erl
  test/keystore_SUITE.erl
  test/mam_jid_mini_SUITE.erl
  test/migration_scripts_SUITE.erl
  test/mod_aws_sns_SUITE.erl
  test/mod_global_distrib_SUITE.erl
  test/mod_offline_mnesia_SUITE.erl
  test/mod_websockets_SUITE.erl
  test/mongoose_cleanup_SUITE.erl
  test/mongoose_config_SUITE.erl
  test/muc_light_SUITE.erl
  test/privacy_SUITE.erl
  test/pubsub_backend_SUITE.erl
  test/roster_SUITE.erl
  test/router_SUITE.erl
Labels: WIP :construction:, waiting-for-review

#2531 Rewrite mod_ping to execute logic in C2S context
  big_tests/tests/mod_ping_SUITE.erl
  include/ejabberd_c2s.hrl
  src/ejabberd_c2s.erl
  src/ejabberd_c2s_info_handler.erl
  src/ejabberd_c2s_state.erl
  src/mod_ping.erl
  src/mongoose_hooks.erl
Labels: WIP :construction:

#2668 Allow for boolean types in REST calls
  src/mongoose_api_common.erl
  src/mongoose_commands.erl
  test/commands_SUITE.erl
Labels: WIP :construction:
