Repository esl/MongooseIM, pull requests merged in 2021-07, with the labels that each got.

#3163 Create a configurable FIFO cache
  big_tests/tests/mam_SUITE.erl
  doc/developers-guide/hooks_description.md
  doc/migrations/4.2.0_4.3.0.md
  doc/modules/mod_cache_users.md
  mkdocs.yml
  rel/files/mongooseim.toml
  rel/mim1.vars-toml.config
  rel/mim2.vars-toml.config
  rel/mim3.vars-toml.config
  src/auth/ejabberd_auth.erl
  src/config/mongoose_config_spec.erl
  src/ejabberd_app.erl
  src/event_pusher/mod_event_pusher_push_plugin_defaults.erl
  src/inbox/mod_inbox.erl
  src/mam/mod_mam.erl
  src/mod_cache_users.erl
  src/mongoose_hooks.erl
  src/mongoose_users.erl
  test/config_parser_SUITE.erl
Labels: to-discuss, waiting-for-review

#3173 Publish a comment from CircleCI to Github
  .circleci/config.yml
  tools/circle-publish-github-comment.sh
Labels: waiting-for-review

#3170 Hosttypyfy wpool
  src/event_pusher/mod_event_pusher_push.erl
  src/event_pusher/mod_event_pusher_sns.erl
  src/mod_push_service_mongoosepush.erl
  src/wpool/mongoose_wpool.erl
  src/wpool/mongoose_wpool_cassandra.erl
  src/wpool/mongoose_wpool_elastic.erl
  src/wpool/mongoose_wpool_generic.erl
  src/wpool/mongoose_wpool_http.erl
  src/wpool/mongoose_wpool_ldap.erl
  src/wpool/mongoose_wpool_mgr.erl
  src/wpool/mongoose_wpool_rdbms.erl
  src/wpool/mongoose_wpool_redis.erl
  src/wpool/mongoose_wpool_riak.erl
  src/wpool/mongoose_wpool_sup.erl
  src/wpool/mongoose_wpool_type_sup.erl
  test/mongoose_wpool_SUITE.erl
Labels: WIP :construction:

#3183 Ci/docker
  .circleci/config.yml
  Makefile
  tools/cache-build.sh
  tools/cache-certs.sh
  tools/cache-tests.sh
  tools/circleci-upload-to-s3.sh
Labels: waiting-for-review

#3174 Hooks rework
  big_tests/tests/mod_ping_SUITE.erl
  big_tests/tests/push_SUITE.erl
  big_tests/tests/sm_SUITE.erl
  src/ejabberd_hooks.erl
  src/ejabberd_sup.erl
  src/gen_hook.erl
  src/mongoose_hooks.erl
  test/auth_tokens_SUITE.erl
  test/commands_SUITE.erl
  test/commands_backend_SUITE.erl
  test/component_reg_SUITE.erl
  test/ejabberd_c2s_SUITE_mocks.erl
  test/ejabberd_hooks_SUITE.erl
  test/ejabberd_sm_SUITE.erl
  test/gen_hook_SUITE.erl
  test/keystore_SUITE.erl
  test/mongoose_cleanup_SUITE.erl
  test/mongooseim_metrics_SUITE.erl
  test/muc_light_SUITE.erl
  test/privacy_SUITE.erl
  test/roster_SUITE.erl
  test/router_SUITE.erl
Labels: waiting-for-review

#3190 Configure CircleCI matrix
  .circleci/config.yml
  rel/files/scripts/bootstrap20-template.escript
Labels: waiting-for-review

#3191 Mam/iq fin transformations
  src/mam/mod_mam.erl
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_params.erl
  src/mam/mod_mam_utils.erl
  test/config_parser_SUITE.erl
Labels: waiting-for-review

#3189 Multitenancy/privacy
  big_tests/dynamic_domains.spec
  big_tests/test.config
  big_tests/tests/privacy_SUITE.erl
  big_tests/tests/privacy_helper.erl
  doc/migrations/4.2.0_4.3.0.md
  include/mod_privacy.hrl
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  rel/files/mongooseim.toml
  rel/mim1.vars-toml.config
  rel/vars-toml.config.in
  src/mod_blocking.erl
  src/mod_privacy_riak.erl
  src/mod_private.erl
  src/mongoose_hooks.erl
  src/privacy/mod_privacy.erl
  src/privacy/mod_privacy_mnesia.erl
  src/privacy/mod_privacy_rdbms.erl
  src/privacy/mod_privacy_riak.erl
Labels: waiting-for-review
