Repository esl/MongooseIM, pull requests merged in 2021-04, with the labels that each got.

#3063 Multi tenancy auth
  big_tests/test.config
  big_tests/tests/dynamic_domains_pm_SUITE.erl
  big_tests/tests/login_SUITE.erl
  big_tests/tests/oauth_SUITE.erl
  include/ejabberd_c2s.hrl
  include/mongoose.hrl
  src/auth/ejabberd_auth.erl
  src/auth/ejabberd_auth_anonymous.erl
  src/auth/ejabberd_auth_dummy.erl
  src/auth/ejabberd_auth_external.erl
  src/auth/ejabberd_auth_http.erl
  src/auth/ejabberd_auth_internal.erl
  src/auth/ejabberd_auth_jwt.erl
  src/auth/ejabberd_auth_ldap.erl
  src/auth/ejabberd_auth_pki.erl
  src/auth/ejabberd_auth_rdbms.erl
  src/auth/ejabberd_auth_riak.erl
  src/auth/ejabberd_gen_auth.erl
  src/config/mongoose_config_parser.erl
  src/config/mongoose_config_spec.erl
  src/domain/mongoose_domain_core.erl
  src/ejabberd_c2s.erl
  src/ejabberd_users.erl
  src/mongoose_client_api/mongoose_client_api.erl
  src/mongoose_credentials.erl
  src/mongoose_scram.erl
  src/sasl/cyrsasl.erl
  src/sasl/cyrsasl_external.erl
  test/auth_dummy_SUITE.erl
  test/auth_external_SUITE.erl
  test/auth_http_SUITE.erl
  test/auth_jwt_SUITE.erl
  test/commands_SUITE.erl
  test/config_parser_SUITE.erl
  test/config_parser_SUITE_data/host_types.options
  test/config_parser_SUITE_data/host_types.toml
  test/ejabberd_c2s_SUITE_mocks.erl
  test/mongoose_domain_core_SUITE.erl
Labels: waiting-for-review

#3066 Prepared queries for chatmarkers and smart_markers
  src/mod_smart_markers_rdbms.erl
  src/offline/mod_offline_chatmarkers_rdbms.erl
Labels: waiting-for-review

#3067 Inbox extensions
  big_tests/default.spec
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_extensions_SUITE.erl
  big_tests/tests/inbox_helper.erl
  doc/migrations/4.1.0_4.x.x.md
  doc/modules/mod_inbox.md
  doc/open-extensions/inbox.md
  include/mod_inbox.hrl
  mkdocs.yml
  priv/mssql2012.sql
  priv/mysql.sql
  priv/pg.sql
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_entries.erl
  src/inbox/mod_inbox_muc.erl
  src/inbox/mod_inbox_muclight.erl
  src/inbox/mod_inbox_one2one.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_rdbms_mssql.erl
  src/inbox/mod_inbox_rdbms_mysql.erl
  src/inbox/mod_inbox_rdbms_pgsql.erl
  src/inbox/mod_inbox_utils.erl
  src/rdbms/mongoose_rdbms.erl
  src/rdbms/mongoose_rdbms_mysql.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/rdbms/rdbms_queries.erl
Labels: waiting-for-review

#3075 Multi tenancy pm
  big_tests/tests/connect_SUITE.erl
  big_tests/tests/dynamic_domains_pm_SUITE.erl
  doc/advanced-configuration/host_config.md
  include/ejabberd_c2s.hrl
  include/mongoose.hrl
  rel/fed1.vars-toml.config
  rel/files/mongooseim.toml
  rel/mim1.vars-toml.config
  rel/mim2.vars-toml.config
  rel/mim3.vars-toml.config
  rel/reg1.vars-toml.config
  rel/vars-toml.config.in
  src/config/mongoose_config_spec.erl
  src/domain/mongoose_domain_core.erl
  src/ejabberd_c2s.erl
  src/ejabberd_local.erl
  src/ejabberd_router.erl
  src/mongoose_hooks.erl
  src/mongoose_router_dynamic_domains.erl
  test/config_parser_SUITE.erl
  test/config_parser_SUITE_data/host_types.options
  test/config_parser_SUITE_data/host_types.toml
  test/config_parser_SUITE_data/miscellaneous.options
  test/config_parser_SUITE_data/miscellaneous.toml
  test/config_parser_SUITE_data/modules.options
  test/config_parser_SUITE_data/modules.toml
  test/config_parser_SUITE_data/mongooseim-pgsql.options
  test/config_parser_SUITE_data/mongooseim-pgsql.toml
  test/config_parser_SUITE_data/outgoing_pools.options
  test/config_parser_SUITE_data/outgoing_pools.toml
  test/config_parser_SUITE_data/s2s_only.options
  test/config_parser_SUITE_data/s2s_only.toml
  test/ejabberd_c2s_SUITE_mocks.erl
  test/ejabberd_config_SUITE_data/mongooseim.minimal.toml
  test/ejabberd_listener_SUITE_data/mongooseim.basic.toml
  test/mongoose_domain_core_SUITE.erl
Labels: WIP :construction:

#3082 Set archive_groupchats to false by default
  src/mam/mod_mam.erl
Labels: waiting-for-ci, waiting-for-review

#3093 Use map for mod_mam:message_row()
  big_tests/default.spec
  big_tests/tests/mam_send_message_SUITE.erl
  big_tests/tests/mam_send_message_SUITE_data/mam_send_message_example.erl
  doc/modules/mod_mam.md
  src/mam/mam_decoder.erl
  src/mam/mam_iq.erl
  src/mam/mam_lookup.erl
  src/mam/mam_send_message.erl
  src/mam/mod_mam.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_elasticsearch_arch.erl
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_muc_cassandra_arch.erl
  src/mam/mod_mam_muc_elasticsearch_arch.erl
  src/mam/mod_mam_params.erl
  src/mam/mod_mam_rdbms_arch.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mam/mod_mam_utils.erl
  src/mod_commands.erl
  src/mod_muc_room.erl
  src/mongoose_client_api/mongoose_client_api_messages.erl
  src/mongoose_client_api/mongoose_client_api_rooms_messages.erl
  src/xml.erl
Labels: waiting-for-review

#3105 Documentation update
  doc/developers-guide/Moving-to-single-app-project-structure.md
  doc/developers-guide/domain_management.md
  doc/user-guide/Features-and-supported-standards.md
  mkdocs.yml
Labels: doc

#3102 Fix Swagger docs rendering
  doc/rest-api/Administration-backend.md
  doc/rest-api/Client-frontend.md
Labels: doc
