Repository esl/MongooseIM, pull requests merged in 2021-12, with the labels that each got.

#3431 Remove wait from unavailable_resources_dont_get_carbons
  big_tests/tests/carboncopy_SUITE.erl
Labels: waiting-for-review

#3432 Run tests in pubsub:basic in parallel
  big_tests/tests/pubsub_SUITE.erl
Labels: waiting-for-review

#3436 Fix sm_SUITE
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/sm_SUITE.erl
Labels: waiting-for-review

#3354 GraphQL in MongooseIM proof of concept
  big_tests/default.spec
  big_tests/dynamic_domains.spec
  big_tests/tests/graphql_SUITE.erl
  big_tests/tests/graphql_SUITE_data/schema.gql
  big_tests/tests/graphql_helper.erl
  big_tests/tests/mongooseimctl_SUITE.erl
  big_tests/tests/mongooseimctl_SUITE_data/schema.gql
  big_tests/tests/rest_helper.erl
  priv/graphql/schemas/admin/admin_schema.gql
  priv/graphql/schemas/user/user_schema.gql
  priv/graphql/spectaql_config.yml
  priv/graphql/wsite/index.html
  rebar.config
  rebar.lock
  rel/fed1.vars-toml.config
  rel/files/mongooseim.toml
  rel/mim2.vars-toml.config
  rel/mim3.vars-toml.config
  rel/reg1.vars-toml.config
  rel/vars-toml.config.in
  src/config/mongoose_config_spec.erl
  src/ejabberd_app.erl
  src/ejabberd_ctl.erl
  src/mongoose_api_common.erl
  src/mongoose_client_api/mongoose_client_api.erl
  src/mongoose_graphql.erl
  src/mongoose_graphql/admin/mongoose_graphql_admin_mutation.erl
  src/mongoose_graphql/admin/mongoose_graphql_admin_query.erl
  src/mongoose_graphql/mongoose_graphql_cowboy_handler.erl
  src/mongoose_graphql/mongoose_graphql_cowboy_response.erl
  src/mongoose_graphql/mongoose_graphql_default.erl
  src/mongoose_graphql/mongoose_graphql_domain.erl
  src/mongoose_graphql/mongoose_graphql_errors.erl
  src/mongoose_graphql/mongoose_graphql_permissions.erl
  src/mongoose_graphql/mongoose_graphql_types.hrl
  src/mongoose_graphql/user/mongoose_graphql_user_mutation.erl
  src/mongoose_graphql/user/mongoose_graphql_user_query.erl
  src/mongooseim.app.src
  test/mongoose_graphql_SUITE.erl
  test/mongoose_graphql_SUITE_data/protected_schema.gql
  test/mongoose_graphql_SUITE_data/schema.gql
  test/mongoose_graphql_SUITE_data/split_schema/mutation.gql
  test/mongoose_graphql_SUITE_data/split_schema/query.gql
  test/mongoose_graphql_SUITE_data/split_schema/root.gql
  test/mongoose_graphql_default_resolver.erl
Labels: waiting-for-review

#3443 Use wait_for_archive_size inside send_rsm_messages helper
  big_tests/tests/mam_helper.erl
Labels: waiting-for-review

#3451 Remove more dead code
  src/admin_extra/service_admin_extra_upload.erl
  src/amp_strategy.erl
  src/domain/service_domain_db.erl
  src/ejabberd.erl
  src/ejabberd_sm.erl
  src/mam/mod_mam_cassandra_arch.erl
  src/mam/mod_mam_muc_cassandra_arch.erl
  src/mam/mod_mam_riak_timed_arch_yz.erl
  src/mod_csi.erl
  src/mod_keystore.erl
  src/mod_private.erl
  src/mod_private_rdbms.erl
  src/mod_private_riak.erl
  src/mod_push_service_mongoosepush.erl
  src/mod_revproxy.erl
  src/mod_websockets.erl
  src/mongoose_acc.erl
  src/mongoose_bin.erl
  src/mongoose_disco.erl
  src/mongoose_http_client.erl
  src/mongoose_iq.erl
  src/mongoose_iq_handler.erl
  src/mongoose_packet_handler.erl
  src/mongoose_privacy.erl
  src/mongoose_rabbit_worker.erl
  src/mongoose_redis.erl
  src/mongoose_riak.erl
  src/mongoose_router_dynamic_domains.erl
  src/mongoose_session.erl
  src/mongoose_xmpp_errors.erl
  src/muc_light/mod_muc_light_room_config.erl
  src/rdbms/mongoose_rdbms.erl
  src/shaper_srv.erl
  src/vcard/mod_vcard_ldap.erl
  src/wpool/mongoose_wpool_type_sup.erl
  src/xml.erl
Labels: waiting-for-review

#3452 Inbox refactor tests
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_extensions_SUITE.erl
  big_tests/tests/inbox_helper.erl
  big_tests/tests/mongoose_helper.erl
Labels: waiting-for-review

#3450 Mam filter property tests
  src/mam/mod_mam_utils.erl
  test/mam_jid_mini_SUITE.erl
  test/mam_misc_SUITE.erl
Labels: waiting-for-review

#3449 Inbox filter bug that puts unnecessary load on the auth backend
  big_tests/tests/inbox_SUITE.erl
  src/inbox/mod_inbox.erl
  src/mam/mod_mam_utils.erl
Labels: bug, ready

#3453 Simplify stream management suite
  big_tests/tests/ct_helper.erl
  big_tests/tests/mongoose_helper.erl
  big_tests/tests/offline_SUITE.erl
  big_tests/tests/sm_SUITE.erl
  big_tests/tests/sm_helper.erl
Labels: waiting-for-review

#3442 GraphQL - extend permissions checking
  priv/graphql/schemas/global/protected_dir.gql
  priv/graphql/schemas/user/user_schema.gql
  src/mongoose_graphql.erl
  src/mongoose_graphql/mongoose_graphql_permissions.erl
  test/mongoose_graphql_SUITE.erl
  test/mongoose_graphql_SUITE_data/permissions_schema.gql
  test/mongoose_graphql_SUITE_data/protected_schema.gql
  test/mongoose_graphql_SUITE_data/schema.gql
Labels: waiting-for-review

#3446 Section-based auth config
  big_tests/test.config
  big_tests/tests/sasl_external_SUITE.erl
  doc/authentication-methods/anonymous.md
  doc/authentication-methods/dummy.md
  doc/authentication-methods/external.md
  doc/authentication-methods/http.md
  doc/authentication-methods/jwt.md
  doc/authentication-methods/ldap.md
  doc/authentication-methods/pki.md
  doc/authentication-methods/rdbms.md
  doc/authentication-methods/riak.md
  doc/configuration/auth.md
  doc/migrations/5.0.0_5.1.0.md
  mkdocs.yml
  rel/files/mongooseim.toml
  rel/mim1.vars-toml.config
  rel/mim2.vars-toml.config
  rel/vars-toml.config.in
  src/auth/mongoose_gen_auth.erl
  src/config/mongoose_config_parser.erl
  src/config/mongoose_config_spec.erl
  test/config_parser_SUITE.erl
  test/config_parser_SUITE_data/host_types.toml
  test/config_parser_SUITE_data/mongooseim-pgsql.toml
  test/config_parser_helper.erl
Labels: waiting-for-review

#3433 Async pools
  big_tests/tests/mam_SUITE.erl
  doc/migrations/5.0.0_5.1.0.md
  doc/modules/mod_mam.md
  src/ejabberd_sup.erl
  src/mam/mod_mam_meta.erl
  src/mam/mod_mam_muc.erl
  src/mam/mod_mam_muc_rdbms_async_pool_writer.erl
  src/mam/mod_mam_rdbms_arch_async.erl
  src/mam/mod_mam_rdbms_async_pool_writer.erl
  src/mam/mod_mam_sup.erl
  src/mongoose_async_pools.erl
  src/mongoose_batch_worker.erl
  test/config_parser_SUITE.erl
  test/config_parser_SUITE_data/modules.toml
  test/config_parser_helper.erl
  test/mod_mam_meta_SUITE.erl
Labels: waiting-for-load-test

#3353 Added mongoose_metrics:ensure_subscribed_metric/3
  src/global_distrib/mod_global_distrib_utils.erl
  src/metrics/mongoose_metrics.erl
  test/mongooseim_metrics_SUITE.erl
Labels: waiting-for-review

#3470 Avoid asking for user exist with a room
  src/inbox/mod_inbox.erl
  src/mam/mod_mam.erl
  src/mongoose_lib.erl
Labels: bug

#3466 Wait for async writers to flush messages in tests
  big_tests/default.spec
  big_tests/dynamic_domains.spec
  big_tests/tests/mam_SUITE.erl
  big_tests/tests/mam_helper.erl
  big_tests/tests/mam_proper_SUITE.erl
  big_tests/tests/rdbms_SUITE.erl
  src/mam/mod_mam_rdbms_arch_async.erl
  src/mongoose_async_pools.erl
  src/mongoose_batch_worker.erl
  src/mongoose_hooks.erl
  src/mongoose_lib.erl
  src/rdbms/mongoose_rdbms_odbc.erl
  src/safely.erl
  test/mongoose_lib_SUITE.erl
  test/safely_SUITE.erl
Labels: waiting-for-review

#3474 GraphQL - Move some big tests to small tests
  big_tests/tests/graphql_SUITE.erl
  big_tests/tests/graphql_helper.erl
  big_tests/tests/mongooseimctl_SUITE.erl
  priv/graphql/schemas/admin/admin_schema.gql
  priv/graphql/schemas/global/auth_status.gql
  priv/graphql/schemas/user/user_auth_status.gql
  priv/graphql/schemas/user/user_schema.gql
  priv/graphql/wsite/index.html
  src/mongoose_graphql.erl
  src/mongoose_graphql/admin/mongoose_graphql_admin_query.erl
  src/mongoose_graphql/mongoose_graphql_enum.erl
  src/mongoose_graphql/user/mongoose_graphql_user_auth_info.erl
  src/mongoose_graphql/user/mongoose_graphql_user_query.erl
  test/mongoose_graphql_SUITE.erl
  test/mongoose_graphql_SUITE_data/listener_schema.gql
Labels: waiting-for-review
