Repository esl/MongooseIM, pull requests merged in 2022-01, with the labels that each got.

#3492 Add fallback to queryid in inbox
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_helper.erl
  src/inbox/mod_inbox.erl
  src/inbox/mod_inbox_entries.erl
Labels: bug, waiting-for-review, waiting-for-ci

#3490 Dependency updates
  rebar.config
  rebar.lock
  src/admin_extra/service_admin_extra_gdpr.erl
  src/ejabberd_admin.erl
  src/mongoose_async_pools.erl
  src/mongooseim.app.src
  test/ejabberd_admin_SUITE.erl
Labels: ready

#3493 Cache muclight affs
  big_tests/tests/muc_light_SUITE.erl
  src/mod_cache_users.erl
  src/mongoose_hooks.erl
  src/muc_light/mod_muc_light.erl
  src/muc_light/mod_muc_light_cache.erl
  src/muc_light/mod_muc_light_room.erl
  test/config_parser_SUITE.erl
Labels: ready

#3500 Inbox/adhoc fixes
  big_tests/tests/inbox_SUITE.erl
  big_tests/tests/inbox_extensions_SUITE.erl
  big_tests/tests/inbox_helper.erl
  src/inbox/mod_inbox_rdbms.erl
  src/inbox/mod_inbox_utils.erl
  src/rdbms/rdbms_queries.erl
Labels: ready

#3483 Stanza api for graphql
  big_tests/default.spec
  big_tests/dynamic_domains.spec
  big_tests/tests/graphql_SUITE.erl
  big_tests/tests/graphql_helper.erl
  big_tests/tests/graphql_stanza_SUITE.erl
  big_tests/tests/mam_helper.erl
  priv/graphql/schemas/admin/admin_schema.gql
  priv/graphql/schemas/admin/stanza.gql
  priv/graphql/schemas/global/jid.gql
  priv/graphql/schemas/global/scalar_types.gql
  priv/graphql/schemas/global/stanza.gql
  src/mam/mod_mam_utils.erl
  src/mod_commands.erl
  src/mod_muc_commands.erl
  src/mongoose_commands.erl
  src/mongoose_graphql.erl
  src/mongoose_graphql/admin/mongoose_graphql_admin_mutation.erl
  src/mongoose_graphql/admin/mongoose_graphql_admin_query.erl
  src/mongoose_graphql/admin/mongoose_graphql_stanza_admin_mutation.erl
  src/mongoose_graphql/admin/mongoose_graphql_stanza_admin_query.erl
  src/mongoose_graphql/mongoose_graphql_errors.erl
  src/mongoose_graphql/mongoose_graphql_helper.erl
  src/mongoose_graphql/mongoose_graphql_scalar.erl
  src/mongoose_lib.erl
  src/mongoose_stanza_api.erl
  src/mongoose_stanza_helper.erl
  test/mongoose_graphql_SUITE.erl
Labels: waiting-for-review
